export var textLiterals = {
  'LANGUAGE': 'JA',
  'VISIT_REPORT': 'Visit Report',
  'COMMISSION_REPORT': 'Commissioning Report',
  'LMRA_REPORT': 'Safety First Report',
  'SMARTBOX_REPORT': 'SmartBox Installations',
  'SPM_REPORT': 'SPM Report',
  'TIME_CONFIRMATION_REPORT': 'Time Confirmation Report',
  'CUSTOMER_DETAILS': 'Customer Details',
  'CONTACT': 'Contact',
  'REPORT_DATE': 'Report date',
  'EQUIPMENT': 'Equipment',
  'RUNNING_HOURS': 'Running Hours',
  'HOURS': 'hours',
  'SERIAL_NUMBER': 'Serial Number',
  'LOAD_HOURS': 'Load Hours',
  'VISIT_DATE': 'Visit date',
  'ORDER_NUMBER': 'Order Number',
  'CONTRACT_NUMBER': 'Contract Number',
  'PO_NUMBER': 'PO number',
  'WORK_COMMENTS': 'Work Comments',
  'NEXT_VISIT': 'Next Visit',
  'NEXT_RECOMMENDED_SERVICE_1': '次回推奨サービス',
  'NEXT_RECOMMENDED_SERVICE_2': '',
  'FOLLOWING_WORK_IS': '追って弊社サービス営業部よりご案内いたします。',
  'ESTIMATED_WORK_HOUR': 'Estimated work hour',
  'TIME_CONFIRMATION': 'Time Confirmation',
  'DATE': 'Date',
  'SERVICE_ENGINEER': 'Service Engineer',
  'ACTIVITY_TYPE': 'Activity Type',
  'HOUR_KM': 'Hour/km',
  'MATERIAL_CONFIRMATION': 'Material Confirmation',
  'PART_NUMBER': 'Part Number',
  'PART_DESCRIPTION': 'Part Description',
  'QUANTITY_UNIT': 'Quantity unit',
  'WORK_DONE': 'Work Done',
  'OPERATIONS': 'Operations',
  'COMMENTS': 'Comments',
  'MEASUREMENT_POINTS': 'Measurement Points',
  'COUNTER': 'Counter',
  'READING_AFTER_SERVICE': 'Reading after service',
  'BEFORE_SERVICE': 'Before service',
  'FROM_LAST_VISIT_ON': 'From last visit on',
  'AUTHORISATION_TO_CARRY': 'ご依頼いただいた作業について',
  'NOTES': '',
  'CUSTOMER_WILL_AGREE': '作業内容（実施項目、使用部品、作業時間）のご確認をお願いたします。尚、正式な注文書を未発行の場合には至急ご発行いただけますようお願いいたします。',
  'CUSTOMER_CONFIRMATION': 'Customer Confirmation',
  'SERVICE_ENGINEER_CONFIRMATION': 'Service Engineer Confirmation',
  'ENTER_YOUR_NAME': 'Enter your name',
  'PLEASE_ENTER_YOUR': 'Please enter your name here',
  'SIGNED_BY': 'Signed by',
  'AT': 'at',
  'BEING_DULY_AUTHORISED': '(Being duly authorised to sign on behalf of the customer)',

  'SAFETY_FIRST': 'Safety First',
  'QUESTION': 'Question',
  'CHECKED': 'Checked',

  'COMPANY_GROUP_NAME': '',
  'COMPANY_LEGAL_NAME': '',
  'VISITORS_ADDRESS_1': '',
  'TELEPHONE': 'Tel',
  'COMPANY_TELEPHONE': '',
  'FOOTER_ADDITIONAL_INFO_1': '',
  'COMPANY_ADDRESS_1': '',
  'VISITOR_ADDRESS_2': '',
  'FAX': 'Fax',
  'COMPANY_FAX': '',
  'FOOTER_ADDITIONAL_INFO_2': '',
  'COMPANY_ADDRESS_2': '',
  'VISITOR_ADDRESS_3': '',
  'COMPANY_URL': '',
  'FOOTER_ADDITIONAL_INFO_3': '',
  'WORKER_DETAIL': 'Worker Detail',
  'WORK_CENTER': 'Work Center',
  'SEARCH_OPTIONS': 'Search Options',
  'DATE_FROM': 'From',
  'DATE_TO': 'To',
  'TOTAL': 'Total',
  'WEEK': 'Week'
};
