import * as EN from "./text-literals-en";
import * as DE from "./text-literals-de";
import * as NL from "./text-literals-nl";
import * as PT from "./text-literals-pt";
import * as FR from "./text-literals-fr";
import * as ES from "./text-literals-es";
import * as RU from "./text-literals-ru";
import * as JA from "./text-literals-ja";
import * as KO from "./text-literals-ko";
import * as TR from "./text-literals-trt-tr";
import * as TRT_TR from "./text-literals-trt-tr";
import * as ASA_DE from "./text-literals-asa-de";
import * as CHJ_EN from "./text-literals-chj-en";
import * as CHJ_FR from "./text-literals-chj-fr";
import * as CHJ_DE from "./text-literals-chj-de";
import * as HRB_HR from "./text-literals-hrb-hr";
import * as SIO_SI from "./text-literals-sio-si";
import * as TEMPLATE_EN from "./text-literals-template-en";
import * as BDA_BA from "./text-literals-bda-ba";
import * as BGA_FR from "./text-literals-bga-fr";
import * as BGA_NL from "./text-literals-bga-nl";
import * as BGK_BG from "./text-literals-bgk-bg";
import * as BQF_PT from "./text-literals-bqf-pt";
import * as CHA_DE from "./text-literals-cha-de";
import * as CHA_FR from "./text-literals-cha-fr";
import * as CHA_IT from "./text-literals-cha-it";
import * as CQA_CN from "./text-literals-cqa-cn";
import * as CQK_ZH from "./text-literals-cqk-zh";
import * as DFS_DE from "./text-literals-dfs-de";
import * as DEC_DE from "./text-literals-dec-de";
import * as DFE_DE from "./text-literals-dfe-de";
import * as DKC_DA from "./text-literals-dkc-da";
import * as NLK_NL from "./text-literals-nlk-nl";
import * as IYA_IT from "./text-literals-iya-it";
import * as INO_EN from "./text-literals-ino-en";
import * as INK_EN from "./text-literals-ink-en";
import * as NLC_NL from "./text-literals-nlc-nl";
import * as CPR_SV from "./text-literals-cpr-sv";
import * as GRC_EL from "./text-literals-grc-el";
import * as NNA_NO from "./text-literals-nna-no";
import * as NFA_FI from "./text-literals-nfa-fi";
import * as LTA_LT from "./text-literals-lta-lt";
import * as LVA_LV from "./text-literals-lva-lv";
import * as CZK_CS from "./text-literals-czk-cs";
import * as SKD_SK from "./text-literals-skd-sk";
import * as HUN_HU from "./text-literals-hun-hu";
import * as PLK_PL from "./text-literals-plk-pl";
import * as ROF_RO from "./text-literals-rof-ro";
import * as GBA_EN from "./text-literals-gba-en";
import * as GBC_EN from "./text-literals-gbc-en";
import * as CHR_DE from "./text-literals-chr-de";
import * as CHR_FR from "./text-literals-chr-fr";
import * as DKA_DA from "./text-literals-dka-da";
import * as SBA_DA from "./text-literals-sba-da";
import * as SBA_EN from "./text-literals-sba-en";
import * as SBA_FI from "./text-literals-sba-fi";
import * as SBA_NO from "./text-literals-sba-no";
import * as SBA_SV from "./text-literals-sba-sv";
import * as IRL_EN from "./text-literals-irl-en";
import * as NLA_NL from "./text-literals-nla-nl";
import * as PRA_PT from "./text-literals-pra-pt";
import * as PEA_ES from "./text-literals-pea-es";
import * as PER_ES from "./text-literals-per-es";
import * as ESA_ES from "./text-literals-esa-es";
import * as AFR_FR from "./text-literals-afr-fr";
import * as FRB_FR from "./text-literals-frb-fr";
import * as ESJ_ES from "./text-literals-esj-es";
import * as RUS_RU from "./text-literals-rus-ru";
import * as ATB_DE from "./text-literals-atb-de";
import * as GCB_EN from "./text-literals-gcb-en";
import * as LMRA_ASA_DE from "./text-literals-lmra-asa-de";
import * as LMRA_GRC_EL from "./text-literals-lmra-grc-el";
import * as COMMISSION from "./text-literals-commission";
import * as KOR_KO from "./text-literals-ko";
import * as USN_EN from "./text-literals-usn-en";
import * as UVB_EN from "./text-literals-uvb-en";
import * as ADE_DE from "./text-literals-ade-de";
import * as CNZ_ZH from "./text-literals-cnz-zh";
import * as IPE_EN from "./text-literals-ipe-en";
import * as RSB_RS from "./text-literals-rsb-rs";
import * as ACA_EN from "./text-literals-aca-en";
import * as ACA_FR from "./text-literals-aca-fr";
import * as MXA_ES from "./text-literals-mxa-es";
import * as MXD_ES from "./text-literals-mxd-es";
import * as HOY_EN from "./text-literals-hoy-en";
import * as UTR_EN from "./text-literals-utr-en";
import * as HKA_EN from "./text-literals-hka-en";
import * as HOK_HK from "./text-literals-hok-hk";
import * as TWN_ZF from "./text-literals-twn-zf";
import * as SEA_EN from "./text-literals-sea-en";
import * as ARG_ES from "./text-literals-arg-es";
import * as BOD_ES from "./text-literals-bod-es";
import * as BRD_PT from "./text-literals-brd-pt";
import * as BRX_PT from "./text-literals-brx-pt";
import * as CJI_ZH from "./text-literals-cji-zh";
import * as CLK_ES from "./text-literals-clk-es";
import * as CLN_ES from "./text-literals-cln-es";
import * as COL_ES from "./text-literals-col-es";
import * as VEN_ES from "./text-literals-ven-es";
import * as AUA_EN from "./text-literals-aua-en";
import * as IDC_EN from "./text-literals-idc-en";
import * as JPP_JA from "./text-literals-jpp-ja";
import * as KRC_KO from "./text-literals-krc-ko";
import * as MMA_EN from "./text-literals-mma-en";
import * as MYS_EN from "./text-literals-mys-en";
import * as NZA_EN from "./text-literals-nza-en";
import * as PHI_EN from "./text-literals-phi-en";
import * as SGC_EN from "./text-literals-sgc-en";
import * as VNE_VI from "./text-literals-vne-vi";
import * as ZDI_TH from "./text-literals-zdi-th";
import * as VNE_EN from "./text-literals-vne-en";

//Cluster 8
import * as AEA_EN from "./text-literals-aea-en";
import * as AEE_EN from "./text-literals-aee-en";
import * as AOC_EN from "./text-literals-aoc-en";
import * as AOC_PT from "./text-literals-aoc-pt";
import * as CZA_CS from "./text-literals-cza-cs";
import * as DZB_EN from "./text-literals-dzb-en";
import * as DZB_FR from "./text-literals-dzb-fr";
import * as EGY_EN from "./text-literals-egy-en";
import * as KEN_EN from "./text-literals-ken-en";
import * as KZB_EN from "./text-literals-kzb-en";
import * as KZB_RU from "./text-literals-kzb-ru";
import * as MAB_EN from "./text-literals-mab-en";
import * as MAB_FR from "./text-literals-mab-fr";
import * as NGR_EN from "./text-literals-ngr-en";
import * as PKA_EN from "./text-literals-pka-en";
import * as PLB_PL from "./text-literals-plb-pl";
import * as RUA_RU from "./text-literals-rua-ru";
import * as RUE_RU from "./text-literals-rue-ru";
import * as SAA_EN from "./text-literals-saa-en";
import * as SAK_EN from "./text-literals-sak-en";
import * as TRC_TR from "./text-literals-trc-tr";
import * as TRF_EN from "./text-literals-trf-en";
import * as TRF_TR from "./text-literals-trf-tr";
import * as TRT_EN from "./text-literals-trt-en";
import * as TRV_EN from "./text-literals-trv-en";
import * as TRV_TR from "./text-literals-trv-tr";
import * as UAA_EN from "./text-literals-UAA-en";
import * as UAA_UK from "./text-literals-UAA-uk";
import * as ZAA_EN from "./text-literals-zaa-en";
import * as ZAX_EN from "./text-literals-zax-en";
import * as ZMC_EN from "./text-literals-zmc-en";

export var textLiterals = {};
export var currentLanguage = 'EN';

textLiterals['EN'] = EN.textLiterals;
textLiterals['DE'] = DE.textLiterals;
textLiterals['NL'] = NL.textLiterals;
textLiterals['PT'] = PT.textLiterals;
textLiterals['FR'] = FR.textLiterals;
textLiterals['ES'] = ES.textLiterals;
textLiterals['RU'] = RU.textLiterals;
textLiterals['JA'] = JA.textLiterals;
textLiterals['KO'] = KO.textLiterals;
textLiterals['TR'] = TRT_TR.textLiterals;
textLiterals['TRT_TR'] = TRT_TR.textLiterals;
textLiterals['ASA_DE'] = ASA_DE.textLiterals;
textLiterals['CQA_CN'] = CQA_CN.textLiterals;
textLiterals['CHJ_EN'] = CHJ_EN.textLiterals;
textLiterals['CHJ_FR'] = CHJ_FR.textLiterals;
textLiterals['CHJ_DE'] = CHJ_DE.textLiterals;
textLiterals['CQK_ZH'] = CQK_ZH.textLiterals;
textLiterals['HRB_HR'] = HRB_HR.textLiterals;
textLiterals['SIO_SI'] = SIO_SI.textLiterals;
textLiterals['TEMPLATE_EN'] = TEMPLATE_EN.textLiterals;
textLiterals['BDA_BA'] = BDA_BA.textLiterals;
textLiterals['BGA_FR'] = BGA_FR.textLiterals;
textLiterals['BGA_NL'] = BGA_NL.textLiterals;
textLiterals['BGK_BG'] = BGK_BG.textLiterals;
textLiterals['BQF_PT'] = BQF_PT.textLiterals;
textLiterals['CHA_DE'] = CHA_DE.textLiterals;
textLiterals['CHA_FR'] = CHA_FR.textLiterals;
textLiterals['CHA_IT'] = CHA_IT.textLiterals;
textLiterals['DFS_DE'] = DFS_DE.textLiterals;
textLiterals['DEC_DE'] = DEC_DE.textLiterals;
textLiterals['DFE_DE'] = DFE_DE.textLiterals;
textLiterals['DKC_DA'] = DKC_DA.textLiterals;
textLiterals['NLK_NL'] = NLK_NL.textLiterals;
textLiterals['IYA_IT'] = IYA_IT.textLiterals;
textLiterals['INO_EN'] = INO_EN.textLiterals;
textLiterals['INK_EN'] = INK_EN.textLiterals;
textLiterals['NLC_NL'] = NLC_NL.textLiterals;
textLiterals['CPR_SV'] = CPR_SV.textLiterals;
textLiterals['GRC_EL'] = GRC_EL.textLiterals;
textLiterals['NNA_NO'] = NNA_NO.textLiterals;
textLiterals['NFA_FI'] = NFA_FI.textLiterals;
textLiterals['LTA_LT'] = LTA_LT.textLiterals;
textLiterals['LVA_LV'] = LVA_LV.textLiterals;
textLiterals['CZK_CS'] = CZK_CS.textLiterals;
textLiterals['SKD_SK'] = SKD_SK.textLiterals;
textLiterals['HUN_HU'] = HUN_HU.textLiterals;
textLiterals['PLK_PL'] = PLK_PL.textLiterals;
textLiterals['ROF_RO'] = ROF_RO.textLiterals;
textLiterals['GBA_EN'] = GBA_EN.textLiterals;
textLiterals['GBC_EN'] = GBC_EN.textLiterals;
textLiterals['CHR_DE'] = CHR_DE.textLiterals;
textLiterals['CHR_FR'] = CHR_FR.textLiterals;
textLiterals['DKA_DA'] = DKA_DA.textLiterals;
textLiterals['SBA_DA'] = SBA_DA.textLiterals;
textLiterals['SBA_EN'] = SBA_EN.textLiterals;
textLiterals['SBA_FI'] = SBA_FI.textLiterals;
textLiterals['SBA_NO'] = SBA_NO.textLiterals;
textLiterals['SBA_SV'] = SBA_SV.textLiterals;
textLiterals['IRL_EN'] = IRL_EN.textLiterals;
textLiterals['NLA_NL'] = NLA_NL.textLiterals;
textLiterals['PRA_PT'] = PRA_PT.textLiterals;
textLiterals['PEA_ES'] = PEA_ES.textLiterals;
textLiterals['PER_ES'] = PER_ES.textLiterals;
textLiterals['ESA_ES'] = ESA_ES.textLiterals;
textLiterals['AFR_FR'] = AFR_FR.textLiterals;
textLiterals['FRB_FR'] = FRB_FR.textLiterals;
textLiterals['ESJ_ES'] = ESJ_ES.textLiterals;
textLiterals['RUS_RU'] = RUS_RU.textLiterals;
textLiterals['ATB_DE'] = ATB_DE.textLiterals;
textLiterals['GCB_EN'] = GCB_EN.textLiterals;
textLiterals['LMRA_ASA_DE'] = LMRA_ASA_DE.textLiterals;
textLiterals['LMRA_GRC_EL'] = LMRA_GRC_EL.textLiterals;
textLiterals['COMMISSION'] = COMMISSION.textLiterals;
textLiterals['KOR_KO'] = KOR_KO.textLiterals;
textLiterals['USN_EN'] = USN_EN.textLiterals;
textLiterals['ADE_DE'] = ADE_DE.textLiterals;
textLiterals['CNZ_ZH'] = CNZ_ZH.textLiterals;
textLiterals['IPE_EN'] = IPE_EN.textLiterals;
textLiterals['RSB_RS'] = RSB_RS.textLiterals;
textLiterals['ACA_EN'] = ACA_EN.textLiterals;
textLiterals['ACA_FR'] = ACA_FR.textLiterals;
textLiterals['MXA_ES'] = MXA_ES.textLiterals;
textLiterals['MXD_ES'] = MXD_ES.textLiterals;
textLiterals['HOY_EN'] = HOY_EN.textLiterals;
textLiterals['UTR_EN'] = UTR_EN.textLiterals;
textLiterals['HKA_EN'] = HKA_EN.textLiterals;
textLiterals['HOK_HK'] = HOK_HK.textLiterals;
textLiterals['TWN_ZF'] = TWN_ZF.textLiterals;
textLiterals['ARG_ES'] = ARG_ES.textLiterals;
textLiterals['BOD_ES'] = BOD_ES.textLiterals;
textLiterals['BRD_PT'] = BRD_PT.textLiterals;
textLiterals['BRX_PT'] = BRX_PT.textLiterals;
textLiterals['CJI_ZH'] = CJI_ZH.textLiterals;
textLiterals['CLK_ES'] = CLK_ES.textLiterals;
textLiterals['CLN_ES'] = CLN_ES.textLiterals;
textLiterals['COL_ES'] = COL_ES.textLiterals;
textLiterals['VEN_ES'] = VEN_ES.textLiterals;
textLiterals['AUA_EN'] = AUA_EN.textLiterals;
textLiterals['IDC_EN'] = IDC_EN.textLiterals;
textLiterals['JPP_JA'] = JPP_JA.textLiterals;
textLiterals['KRC_KO'] = KRC_KO.textLiterals;
textLiterals['MMA_EN'] = MMA_EN.textLiterals;
textLiterals['MYS_EN'] = MYS_EN.textLiterals;
textLiterals['NZA_EN'] = NZA_EN.textLiterals;
textLiterals['PHI_EN'] = PHI_EN.textLiterals;
textLiterals['SGC_EN'] = SGC_EN.textLiterals;
textLiterals['SEA_EN'] = SEA_EN.textLiterals;
textLiterals['UVB_EN'] = UVB_EN.textLiterals;
textLiterals['VNE_VI'] = VNE_VI.textLiterals;
textLiterals['ZDI_TH'] = ZDI_TH.textLiterals;
textLiterals['VNE_EN'] = VNE_EN.textLiterals;

//Cluster 8
textLiterals['AEA_EN'] = AEA_EN.textLiterals;
textLiterals['AEE_EN'] = AEE_EN.textLiterals;
textLiterals['AOC_EN'] = AOC_EN.textLiterals;
textLiterals['AOC_PT'] = AOC_PT.textLiterals;
textLiterals['CZA_CS'] = CZA_CS.textLiterals;
textLiterals['DZB_EN'] = DZB_EN.textLiterals;
textLiterals['DZB_PT_EN'] = DZB_EN.textLiterals;
textLiterals['DZB_FR'] = DZB_FR.textLiterals;
textLiterals['DZB_PT_FR'] = DZB_FR.textLiterals;
textLiterals['EGY_EN'] = EGY_EN.textLiterals;
textLiterals['EGY_PT_EN'] = EGY_EN.textLiterals;
textLiterals['KEN_EN'] = KEN_EN.textLiterals;
textLiterals['KEN_PT_EN'] = KEN_EN.textLiterals;
textLiterals['KZB_RU'] = KZB_RU.textLiterals;
textLiterals['MAB_EN'] = MAB_EN.textLiterals;
textLiterals['MAB_FR'] = MAB_FR.textLiterals;
textLiterals['NGR_EN'] = NGR_EN.textLiterals;
textLiterals['NGR_PT_EN'] = NGR_EN.textLiterals;
textLiterals['PKA_EN'] = PKA_EN.textLiterals;
textLiterals['PLB_PL'] = PLB_PL.textLiterals;
textLiterals['RUA_RU'] = RUA_RU.textLiterals;
textLiterals['RUE_RU'] = RUE_RU.textLiterals;
textLiterals['SAA_EN'] = SAA_EN.textLiterals;
textLiterals['SAK_EN'] = SAK_EN.textLiterals;
textLiterals['TRT_EN'] = TRT_EN.textLiterals;
textLiterals['TRT_TR'] = TRT_TR.textLiterals;
textLiterals['TRC_TR'] = TRC_TR.textLiterals;
textLiterals['TRF_TR'] = TRF_TR.textLiterals;
textLiterals['TRV_EN'] = TRV_EN.textLiterals;
textLiterals['TRV_TR'] = TRV_TR.textLiterals;
textLiterals['UAA_EN'] = UAA_EN.textLiterals;
textLiterals['UAA_UK'] = UAA_UK.textLiterals;
textLiterals['ZAA_EN'] = ZAA_EN.textLiterals;
textLiterals['ZAX_EN'] = ZAX_EN.textLiterals;
textLiterals['ZMC_EN'] = ZMC_EN.textLiterals;
textLiterals['ZMC_PT_EN'] = ZMC_EN.textLiterals;
