export var textLiterals = {
  'LANGUAGE': 'EL',
  'VISIT_REPORT': 'Δελτίο επίσκεψης',
  'COMMISSION_REPORT': 'Δελτίο επίσκεψης',
  'LMRA_REPORT': 'LMRA Δελτίο',
  'SMARTBOX_REPORT': 'SMARTBOX Δελτίο',
  'SPM_REPORT': 'SPM Δελτίο',
  'TIME_CONFIRMATION_REPORT': 'Αναφορά επιβεβαίωσης χρόνου',
  'CUSTOMER_DETAILS': 'Στοιχεία πελάτη',
  'CONTACT': 'Όνομα επαφής',
  'REPORT_DATE': 'Ημερομηνία Δελτίου',
  'EQUIPMENT': 'Εξοπλισμός',
  'RUNNING_HOURS': 'Ώρες λειτουργίας',
  'HOURS': 'Ώρες',
  'SERIAL_NUMBER': 'Αριθμός σειράς',
  'LOAD_HOURS': 'Ώρες φορτίου',
  'VISIT_DATE': 'Ημερομηνία επίσκεψης',
  'ORDER_NUMBER': 'Αρ.Παραγγελίας',
  'CONTRACT_NUMBER': 'Αρ.Συμβολαίου',
  'PO_NUMBER': 'Αρ.Εντολής αγοράς',
  'WORK_COMMENTS': 'Σχόλια',
  'NEXT_VISIT': 'Επόμενη επίσκεψη',
  'NEXT_RECOMMENDED_SERVICE_1': 'Προτεινόμενη επόμενη συντηρηση 1',
  'NEXT_RECOMMENDED_SERVICE_2': 'Προτεινόμενη επόμενη συντηρηση 2',
  'FOLLOWING_WORK_IS': 'Επόμενη εργασία',
  'ESTIMATED_WORK_HOUR': 'Εκτιμώμενες ώρες ',
  'TIME_CONFIRMATION': 'Επιβεβαίωση χρόνου',
  'DATE': 'Ημερομηνία',
  'SERVICE_ENGINEER': 'Τεχνικός',
  'ACTIVITY_TYPE': 'Τύπος δραστηριότητας',
  'HOUR_KM': 'Ώρες/Χλμ',
  'MATERIAL_CONFIRMATION': 'Επιβεβαίωση υλικού',
  'PART_NUMBER': 'Αρ.Υλικού',
  'PART_DESCRIPTION': 'Αρ.Υλικού',
  'QUANTITY_UNIT': 'Ποσότητα μοναδας',
  'WORK_DONE': 'Ολοκλήρωση εργασιών',
  'OPERATIONS': 'Εργασίες',
  'COMMENTS': 'Εργασίες',
  'MEASUREMENT_POINTS': 'Σημεία μέτρησης',
  'COUNTER': 'Μετρητής',
  'READING_AFTER_SERVICE': 'Μέτρηση μετά τη συντήρηση',
  'BEFORE_SERVICE': 'Μέτρηση πριν τη συντήρηση',
  'FROM_LAST_VISIT_ON': 'Μέτρηση πριν τη συντήρηση',
  'AUTHORISATION_TO_CARRY': 'Εξουσιοδοτηση',
  'NOTES': 'Σχόλια',
  'CUSTOMER_WILL_AGREE': 'Συγκατάθεση πελάτη',
  'CUSTOMER_CONFIRMATION': 'Επιβεβαίωση πελάτη',
  'SERVICE_ENGINEER_CONFIRMATION': 'Επιβεβαίωση τεχνικού',
  'ENTER_YOUR_NAME': 'Ονομα',
  'PLEASE_ENTER_YOUR': 'Όνομα',
  'SIGNED_BY': 'Υπογραφή από',
  'AT': 'στις',
  'BEING_DULY_AUTHORISED': 'Πλήρως εξουσιοδοτημένος να υπογράφει εξ ονόματος του πελατη',

  'SAFETY_FIRST': 'Safety First',
  'QUESTION': 'Ερώτηση',
  'CHECKED': 'Έλεγχος',

  'COMPANY_GROUP_NAME': 'ΑΤΛΑΣ ΚΟΠΚΟ ΕΛΛΑΣ ΑΕ',
  'COMPANY_LEGAL_NAME': '',
  'VISITORS_ADDRESS': '',
  'TELEPHONE': 'Τηλ.',
  'COMPANY_TELEPHONE': '+302103499600',
  'FOOTER_ADDITIONAL_INFO_1': 'ALPHA BANK:106-002320-000256',
  'COMPANY_ADDRESS_1': 'Λ.Κορωπίου Βάρης 82',
  'VISITOR_ADDRESS_1': 'Λ.Κορωπίου Βάρης 82',
  'FAX': 'Fax',
  'COMPANY_FAX': '+302103454783',
  'FOOTER_ADDITIONAL_INFO_2': 'ETE:140-47040531',
  'COMPANY_ADDRESS_2': '19400 Θέση Κλώσσαρι Κορωπί',
  'VISITOR_ADDRESS_2': '19400 Θέση Κλώσσαρι Κορωπί',
  'COMPANY_URL': 'www.atlascopco.com.gr',
  'FOOTER_ADDITIONAL_INFO_3': 'EUROBANK:0026.0040.6702.0050.0043',
  'WORKER_DETAIL': 'Στοιχεία τεχνικού',
  'WORK_CENTER': 'Τεχνικός',
  'SEARCH_OPTIONS': 'Επιλογή αναζήτησης',
  'DATE_FROM': 'Από',
  'DATE_TO': 'Εως',
  'TOTAL': 'Σύνολο',
  'WEEK': 'Εβδομάδα'
};
