export var textLiterals = {
  'VISIT_REPORT': 'Besuchsbericht',
  'COMMISSION_REPORT': 'G - Commissioning Report',
  'LMRA_REPORT': 'G - Safety First Report',
  'SMARTBOX_REPORT': 'G - SmartBox Installations',
  'SPM_REPORT': 'G - SPM Report',
  'TIME_CONFIRMATION_REPORT': 'G - Time Confirmation Report',
  'CUSTOMER_DETAILS': 'Kundendetails',
  'CONTACT': 'Ansprechpartner',
  'REPORT_DATE': 'Erstellungsdatum',
  'EQUIPMENT': 'Equipment',
  'RUNNING_HOURS': 'Betriebsstunden',
  'HOURS': 'Stunden',
  'SERIAL_NUMBER': 'Seriennummer',
  'LOAD_HOURS': 'Laststunden',
  'VISIT_DATE': 'Einsatzdatum',
  'ORDER_NUMBER': 'Auftragsnummer',
  'CONTRACT_NUMBER': 'Vertragsnummer',
  'PO_NUMBER': 'Bestellnummer',
  'WORK_COMMENTS': 'Arbeitsbeschreibung',
  'NEXT_VISIT': 'G - Next Visit',
  'NEXT_RECOMMENDED_SERVICE_1': 'G - Next recommended service is a “',
  'NEXT_RECOMMENDED_SERVICE_2': 'G - ” estimated due date',
  'FOLLOWING_WORK_IS': 'G - Following work is recommended, our service sales will contact you',
  'ESTIMATED_WORK_HOUR': 'G - Estimated work hour',
  'TIME_CONFIRMATION': 'Zeitbestätigung',
  'DATE': 'Datum',
  'SERVICE_ENGINEER': 'Monteur',
  'ACTIVITY_TYPE': 'Leistungsart',
  'HOUR_KM': 'Stunden/Kilometer',
  'MATERIAL_CONFIRMATION': 'Ersatzteilbestätigung',
  'PART_NUMBER': 'Ersatzteilnummer',
  'PART_DESCRIPTION': 'Ersatzteilbezeichnung',
  'QUANTITY_UNIT': 'Mengeneinheit',
  'WORK_DONE': 'Durchgeführte Arbeiten',
  'OPERATIONS': 'Tätigkeiten',
  'COMMENTS': 'Kommentare',
  'MEASUREMENT_POINTS': 'Messpunkte',
  'COUNTER': 'Zähler',
  'READING_AFTER_SERVICE': 'Stand nach dem Service',
  'BEFORE_SERVICE': 'Stand vor dem Service',
  'FROM_LAST_VISIT_ON': 'Stand seit dem letzten Service am',
  'AUTHORISATION_TO_CARRY': 'G - AUTHORISATION TO CARRY OUT WORK WITH/WITHOUT AN ORDER NO.',
  'NOTES': 'Hinweis',
  'CUSTOMER_WILL_AGREE': 'In Kürze erhalten Sie von uns eine Kundenzufriedenheitsbefragung per Mail. Ihre Rückmeldung ist für uns sehr wichtig, um unser Serviceangebot für Sie weiter auszubauen und zu verbessern. Die Teilnahme ist natürlich freiwillig. Vielen Dank für Ihre Unterstützung.',
  'CUSTOMER_CONFIRMATION': 'Unterschrift Kunde',
  'SERVICE_ENGINEER_CONFIRMATION': 'Unterschrift Servicetechniker',
  'ENTER_YOUR_NAME': 'G - Enter your name',
  'PLEASE_ENTER_YOUR': 'G - Please enter your name here',
  'SIGNED_BY': 'Unterschrieben',
  'AT': 'am',
  'BEING_DULY_AUTHORISED': 'Authorisiert',

  'SAFETY_FIRST': 'Safety First',
  'QUESTION': 'Question',
  'CHECKED': 'Checked',

  'COMPANY_GROUP_NAME': 'Atlas Copco Kompressoren und Drucklufttechnik GmbH',
  'COMPANY_LEGAL_NAME': 'Langemarckstr. 35',
  'VISITORS_ADDRESS': 'Tel: +49 (0)201 2177-0',
  'TELEPHONE': 'Tel',
  'COMPANY_TELEPHONE': '+31 (0)78 6230 230',
  'FOOTER_ADDITIONAL_INFO_1': 'Bankverbindung SEB AG',
  'COMPANY_ADDRESS_1': 'D-45141 Essen',
  'VISITOR_ADDRESS_1': 'Fax: +49 (0)201 216917',
  'FAX': 'Fax',
  'COMPANY_FAX': '+31 (0)78 6230 242',
  'FOOTER_ADDITIONAL_INFO_2': 'SEB Merchant Banking',
  'COMPANY_ADDRESS_2': 'Postfach 10 02 51',
  'VISITOR_ADDRESS_2': 'info.kompressoren@de.atlascopco.com',
  'COMPANY_URL': 'www.atlascopco.nl',
  'FOOTER_ADDITIONAL_INFO_3': 'IBAN-Code:DE79512202000030058008',
  'WORKER_DETAIL': 'G - Worker Detail',
  'WORK_CENTER': 'G - Work Center',
  'SEARCH_OPTIONS': 'G - Search Options',
  'DATE_FROM': 'G- From',
  'DATE_TO': 'G -To',
  'TOTAL': 'Total',
  'WEEK': 'Week'
};
