export var textLiterals = {
  'VISIT_REPORT': 'Besuchsbericht',
  'COMMISSION_REPORT': 'Inbetriebnahmeprotokoll',
  'LMRA_REPORT': 'LMRA Rapport',
  'SMARTBOX_REPORT': 'Smartboxreport',
  'SPM_REPORT': 'SPM Report',
  'TIME_CONFIRMATION_REPORT': 'Zeitbestätigung',
  'CUSTOMER_DETAILS': 'Kundendaten',
  'CONTACT': 'Kontaktperson',
  'REPORT_DATE': 'Datum',
  'EQUIPMENT': 'Maschine',
  'RUNNING_HOURS': 'Betriebsstunden',
  'HOURS': 'Stunden',
  'SERIAL_NUMBER': 'Seriennummer',
  'LOAD_HOURS': 'Laststunden',
  'VISIT_DATE': 'Servicedatum',
  'ORDER_NUMBER': 'Auftragsnummer',
  'CONTRACT_NUMBER': 'Vertragsnummer',
  'PO_NUMBER': 'Kundenbestellzeichen',
  'WORK_COMMENTS': 'Arbeitsbericht',
  'NEXT_VISIT': 'Nächster Besuch',
  'NEXT_RECOMMENDED_SERVICE_1': 'Wir empfehlen den nächste Service “',
  'NEXT_RECOMMENDED_SERVICE_2': '” durchführen zu lassen am.',
  'FOLLOWING_WORK_IS': 'Wir werden Ihnen ein Angebot für diese Arbeiten zusenden.',
  'ESTIMATED_WORK_HOUR': 'Geschätze Dauer',
  'TIME_CONFIRMATION': 'Arbeitszeit',
  'DATE': 'Datum',
  'SERVICE_ENGINEER': 'Servicetechniker',
  'ACTIVITY_TYPE': 'Beschreibung',
  'HOUR_KM': 'Anzahl',
  'MATERIAL_CONFIRMATION': 'Artikelliste',
  'PART_NUMBER': 'Artikelnummer',
  'PART_DESCRIPTION': 'Bezeichnung',
  'QUANTITY_UNIT': 'Anzahl',
  'WORK_DONE': 'Durchgeführte Arbeiten',
  'OPERATIONS': 'Tätigkeiten',
  'COMMENTS': 'Anmerkungen',
  'MEASUREMENT_POINTS': 'Messpunkte',
  'COUNTER': 'Messwert',
  'READING_AFTER_SERVICE': 'nach dem Service',
  'BEFORE_SERVICE': 'vor dem Service',
  'FROM_LAST_VISIT_ON': 'beim letzten Service',
  'AUTHORISATION_TO_CARRY': 'Mit Ihrer Unterschrift wird die Richtigkeit der eingetragenen Angaben bestätigt.',
  'NOTES': 'Anmerkungen',
  'CUSTOMER_WILL_AGREE': 'In Kürze erhalten Sie von uns eine Kundenzufriedenheitsbefragung per Mail. Ihre Rückmeldung ist für uns sehr wichtig, um unser Serviceangebot für Sie weiter auszubauen und zu verbessern. Die Teilnahme ist natürlich freiwillig. Vielen Dank für Ihre Unterstützung.',
  'CUSTOMER_CONFIRMATION': 'Unterschrift des Kunden',
  'SERVICE_ENGINEER_CONFIRMATION': 'Unterschrift des Servicetechnikers',
  'ENTER_YOUR_NAME': 'Geben Sie Ihren Namen ein',
  'PLEASE_ENTER_YOUR': 'Bitte geben Sie hier Ihren Namen ein',
  'SIGNED_BY': 'Unterschrieben von',
  'AT': 'am',
  'TELEPHONE': 'Tel',
  'BEING_DULY_AUTHORISED': '(Rechtsverbindliche Unterschrift)',

  'SAFETY_FIRST': 'Sicherheitsfragebogen',
  'QUESTION': 'Frage',
  'CHECKED': 'Geprüft',

  'COMPANY_LEGAL_NAME': '',

  'FOOTER_ADDITIONAL_INFO_1': 'Bank: Deutsche Bank 8001 Zürich IBAN:CH63 8780 1001 0008 5800 3 (CHF)',

  'COMPANY_ADDRESS_1': 'Aeschwuhrstrasse 54',

  'VISITOR_ADDRESS_1': 'Tel.               062 789 75 75',

  'FOOTER_ADDITIONAL_INFO_2': 'IBAN:CH36 8780 1001 0008 5800 4 (EUR) BIC/SWIFT:DEUTCHZZXXX',

  'COMPANY_GROUP_NAME': 'SERVATECHNIK AG, Druckluftanlagen',

  'COMPANY_ADDRESS_2': 'CH-4665 Oftringen',

  'VISITORS_ADDRESS': 'Tel. Service 062 789 75 55',

  'VISITOR_ADDRESS_2': 'Fax               062 789 76 76',

  'COMPANY_URL': 'www.servatechnik.ch',

  'FOOTER_ADDITIONAL_INFO_3': 'MWST/TVA:CHE-105.955.896',

  'FOOTER_CENTER_LINE1': 'service@servatechnik.ch',

  'COMPANY_FAX': 'info@servatechnik.ch',
  'WORKER_DETAIL': 'NL - Worker Detail',
  'WORK_CENTER': 'NL - Work Center',
  'SEARCH_OPTIONS': 'NL - Search Options',
  'DATE_FROM': 'NL -From',
  'DATE_TO': 'NL - To',
  'TOTAL': 'Total',
  'WEEK': 'Woche',

  'FAX': 'Fax',

  //Commissioning Reporting literals

  'COMM_TEXT1': 'Inbetriebnahmeprotokoll',
  'COMM_TEXT2': 'Die Inbetriebnahme Ihres Equipments ist für uns von größter Bedeutung. Eine korrekte Inbetriebnahme ist der erste Schritt für die zukünftige, lückenlose Verfolgung der Maschinengeschichte des Equipments. Während der Inbetriebnahme registriert der Kundendiensttechniker die ersten Ablesungen und andere Betriebsdaten der Maschine. Alle Temperaturen, Drücke, Spannungen etc. werden mit den richtigen Instrumenten und Anzeigen genau registriert. Die Servicedaten im Inbetriebnahmeprotokoll sind auch zu einem späteren Zeitpunkt eine wichtige Bezugsquelle. Sie werden unter anderem beim Auftreten eines Problems oder eines Betriebsausfalls benötigt. Werden die Servicedaten während der Inbetriebnahme nicht registriert, ist der Vergleich zu diesen später nicht oder nur unvollständig möglich und anfallende Gewährleistungsansprüche werden abgelehnt. Dieses Inbetriebnahmeprotokoll ist als schriftliches Arbeitsprogramm zur Durchführung des Erprobungsbetriebes gültig. Es beinhaltet nicht die Inbetriebnahme im Sinne der Betriebssicherheitsverordnung.',
  'COMM_TEXT3': 'Inbetriebnahmeprüfung',
  'COMM_TEXT4': 'Prüfung',
  'COMM_TEXT5': 'Kommentare',
  'COMM_Q1_Q': '1. Die Installation erfolgt durch',
  'COMM_Q1_A1': 'Atlas Copco',
  'COMM_Q1_A2': 'Kunde',
  'COMM_Q2_Q': '2. Elektrischer Anschluss erfolgt durch',
  'COMM_Q2_A1': 'Atlas Copco',
  'COMM_Q2_A2': 'Kunde',
  'COMM_Q3_Q': '3. Beschädigungen an der Anlage',
  'COMM_Q3_A1': 'Ja',
  'COMM_Q3_A2': 'Nein',
  'COMM_Q3_A3': 'Wenn ja, wo…',
  'COMM_Q4_Q': '4. Korrosion an der Analge',
  'COMM_Q4_A1': 'Ja',
  'COMM_Q4_A2': 'Nein',
  'COMM_Q4_A3': 'Wenn ja, wo…',
  'COMM_Q5_Q': 'Umgebungsbedingungen',
  'COMM_Q5_A1': 'Sauber',
  'COMM_Q5_A2': 'Dreckig',
  'COMM_Q5_A3': 'Sehr dreckig',
  'COMM_Q6_Q': '6. Kompressorraum richtig belüftet',
  'COMM_Q6_A1': 'Ja',
  'COMM_Q6_A2': 'Nein',
  'COMM_Q7_Q': '7. Stehen andere Kompressoren im gleichen Raum',
  'COMM_Q7_A1': 'Ja',
  'COMM_Q7_A2': 'Nein',
  'COMM_Q7_A3': 'Wenn ja…',
  'COMM_Q8_Q': '8. Fundament OK',
  'COMM_Q8_A1': 'Ja',
  'COMM_Q8_A2': 'Nein',
  'COMM_Q9_Q': '9. Einlass- und/oder Auslasskanäle verwendet',
  'COMM_Q9_A1': 'Nur Einlass',
  'COMM_Q9_A2': 'Nur Auslass',
  'COMM_Q9_A3': 'Beides Einlass/Auslass',
  'COMM_Q10_Q': '10. Lufteinlassqualität OK',
  'COMM_Q10_A1': 'Ja',
  'COMM_Q10_A2': 'Nein',
  'COMM_Q11_Q': 'Luftauslass OK',
  'COMM_Q11_A1': 'Ja',
  'COMM_Q11_A2': 'Nein',
  'COMM_Q12_Q': '12. Luftaustrittsrohr OK',
  'COMM_Q12_A1': 'Ja',
  'COMM_Q12_A2': 'Nein',
  'COMM_Q13_Q': 'Druckluftbehälter installiert',
  'COMM_Q13_A1': 'Ja',
  'COMM_Q13_A2': 'Nein',
  'COMM_Q13_A3': 'Volumen',
  'COMM_Q13_A4': 'l',
  'COMM_Q14_Q': '14. Filter, die hinter dem Kompressor installiert sind',
  'COMM_Q14_A1': 'Ja',
  'COMM_Q14_A2': 'Nein',
  'COMM_Q14_A3': 'Wenn ja…',
  'COMM_Q15_Q': '15. Trockner installiert',
  'COMM_Q15_A1': 'Ja',
  'COMM_Q15_A2': 'Nein',
  'COMM_Q15_A3': 'Wenn ja…',
  'COMM_Q16_Q': '16. Kühlwasserqualität OK',
  'COMM_Q16_A1': 'Ja',
  'COMM_Q16_A2': 'Nein',
  'COMM_Q17_Q': '17. Kühlwasserdurchfluss l/s',
  'COMM_Q17_A1': 'Ja',
  'COMM_Q17_A2': 'Nein',
  'COMM_Q17_A3': 'l/s',
  'COMM_Q18_Q': '18. Kondensat läuft in',
  'COMM_Q18_A1': 'Öl-/Wasserfilter',
  'COMM_Q18_A2': 'Kanalisation',
  'COMM_Q19_Q': '19. Spannung',
  'COMM_Q20_Q': '20. Frequenz',
  'COMM_Q21_Q': '21. Überlasteinstellung des Hauptmotors',
  'COMM_Q22_Q': '22. Überlasteinstellung des/der Lüftermotor(en)',
  'COMM_Q23_Q': '23. Be-/Entladedruck',
  'COMM_Q23_A1': 'Bar',
  'COMM_Q24_Q': '24. Einweisung des Kunden ins Elektronikon',
  'COMM_Q24_A1': 'Ja',
  'COMM_Q24_A2': 'Nein',
  'COMM_Q25_Q': '25.',
  'COMM_Q25_A1': 'Zusätzliche Prüfung…',
  'COMM_Q26_Q': '26.',
  'COMM_Q26_A1': 'Zusätzliche Prüfung…',
  'COMM_Q27_Q': '27.',
  'COMM_Q27_A1': 'Zusätzliche Prüfung…',
  'COMM_Q28_Q': '28. Messgerät',
  'COMM_Q29_Q': '29. Seriennummer',
  'COMM_Q30_Q': '30. Zertifikatsnummer'

};
