export var textLiterals = {

  'VISIT_REPORT': 'Servis Raporu',
  'COMMISSION_REPORT': 'İlk calıstırma raporu',
  'LMRA_REPORT': 'Is güvenligi raporu',
  'SMARTBOX_REPORT': 'Smartbox kurulum',
  'SPM_REPORT': 'SPM raporu',
  'TIME_CONFIRMATION_REPORT': 'Zaman Teyid Raporu',
  'CUSTOMER_DETAILS': 'Müsteri Detayları',
  'CONTACT': 'Kontak Kişi',
  'REPORT_DATE': 'Rapor Tarihi',
  'EQUIPMENT': 'Ekipman',
  'RUNNING_HOURS': 'Çalışma Saati',
  'HOURS': 'Saatler',
  'SERIAL_NUMBER': 'Seri No',
  'LOAD_HOURS': 'Yükte Çalısma Saati',
  'VISIT_DATE': 'Servis Tarihi',
  'ORDER_NUMBER': 'Order Numarası',
  'CONTRACT_NUMBER': 'Kontrat No:',
  'PO_NUMBER': 'PO Numarası',
  'ORDER_DESCRIPTION': 'Sipariş açıklaması',
  'WORK_COMMENTS': 'Servis  Acıklama',
  'NEXT_VISIT': 'Gelecek Servis Ziyareti',
  'NEXT_RECOMMENDED_SERVICE_1': 'Onerilen gelecek servis “',
  'NEXT_RECOMMENDED_SERVICE_2': '” Tahmini tarih',
  'FOLLOWING_WORK_IS': 'Belirtilen servis/ bakım önerilmektedir. Satıs Mühendisimiz sizinle baglantıya gececektir',
  'ESTIMATED_WORK_HOUR': 'Tahmini Çalışma Süresi',
  'TIME_CONFIRMATION': 'Zaman Teyidi',
  'DATE': 'Tarih',
  'SERVICE_ENGINEER': 'Servis Mühendisi',
  'ACTIVITY_TYPE': 'Aktivite tipi',
  'HOUR_KM': 'Saat /km',
  'MATERIAL_CONFIRMATION': 'Parça Listesi',
  'PART_NUMBER': 'Parça numarası',
  'PART_DESCRIPTION': 'Parça Tanımı',
  'QUANTITY_UNIT': 'Adet',
  'WORK_DONE': 'Yapılan is',
  'OPERATIONS': 'Operasyon',
  'COMMENTS': 'Acıklama',
  'MEASUREMENT_POINTS': 'Olcüm Noktaları',
  'COUNTER': 'Ölçüm Noktası',
  'READING_AFTER_SERVICE': 'Servis Sonrası',
  'BEFORE_SERVICE': 'Servis Öncesi',
  'FROM_LAST_VISIT_ON': 'Son Servis',
  'AUTHORISATION_TO_CARRY': 'SİPARIŞ NOSU İLE VEYA SİPARİŞ NOSU OLMADAN ÇALIŞMA İLE İLGİLİ YETKİLENDİRME',
  'NOTES': 'Notlar',
  'CUSTOMER_WILL_AGREE1': '1. Değerli Müşterimiz iş bitiminde e-mail ile gönderilecek müşteri memnuiyet  anketimizi yanıtlamanızı rica ederiz.',
  'CUSTOMER_WILL_AGREE2': '2. Bakım esnasında orijinal parçalar tam ve eksiksiz olarak kullanılarak, çıkan parçalar müşteriye eksiksiz olarak teslim edilmiştir.',
  'CUSTOMER_CONFIRMATION': 'Müşteri Yetkilisi',
  'SERVICE_ENGINEER_CONFIRMATION': 'Atlas Copco Yetkilisi',
  'ENTER_YOUR_NAME': 'Ismini gir',
  'PLEASE_ENTER_YOUR': 'Ismini bu alana gir',
  'SIGNED_BY': 'Imzalayan',
  'AT': 'at',
  'BEING_DULY_AUTHORISED': '',
  'LMRA_ENABLED_IN_VISIT_REPORT': 'false',
  'SAFETY_FIRST': 'Safety First',
  'QUESTION': 'Soru',
  'CHECKED': 'Kontrol Edildi',

  'COMPANY_GROUP_NAME': 'Atlas Copco Turkey',
  'COMPANY_LEGAL_NAME': 'Atlas Copco Makinaları Imalat A.Ş.',
  'VISITORS_ADDRESS': '',
  'TELEPHONE': 'Telefon:',
  'COMPANY_TELEPHONE': '+90 (0)216 581 0581',
  'FOOTER_ADDITIONAL_INFO_1': 'Tic.Sic.No 103921/50182',
  'COMPANY_ADDRESS_1': 'Istasyon Mah. İbiş Ağa Cad. No: 6',
  'VISITOR_ADDRESS_1': '',
  'FAX': 'Faks:',
  'COMPANY_FAX': '  +90 (0)216 581 0582',
  'FOOTER_ADDITIONAL_INFO_2': 'Yenikapı V.D 1020044563',
  'COMPANY_ADDRESS_2': '34940 Tuzla, Istanbul-Türkiye',
  'VISITOR_ADDRESS_2': '',
  'COMPANY_URL': 'www.atlascopco.com.tr',
  'FOOTER_ADDITIONAL_INFO_3': 'Mersis No: 0102004456300016',
  'WORKER_DETAIL': 'Calısan Detayı',
  'WORK_CENTER': 'Calısm Merkezi',
  'SEARCH_OPTIONS': 'Ara opsiyonları',
  'DATE_FROM': 'Kimden',
  'DATE_TO': 'Kime',
  'TOTAL': 'Toplam',
  'WEEK': 'Hafta',
  'COMM_TEXT1': 'İlk çalıştırma prosedürü ',
'COMM_TEXT2': 'Bir kompresörün devreye alınması özel bir öneme sahiptir. Doğru devreye alma ekipman geçmişini oluşturmanın ilk adımıdır.Ekipman geçmişi doğru takip için çok önemlidir. Devreye alma süresince servis mühendisi ilk servis okumalarını ve diğer ekipman çalışma verilerini kaydedecektir.Tüm sıcaklık, basınç, voltaj amper...vb doğru servis aletleri ve ölçü aletleri kullanılarak kaydedilmelidir.Devriye alma raporundaki servis verileri daha sonraki bir aşamada önemli bir referans kaynağı olacaktır.Herhangi bir servis problemini tartışırken referans olarak kullanabilirsiniz.Servis okumaları devreye alma aşamasında kaydedilmemişse daha sonraki durumda karşılaştırılması oldukça zor olabilir. ',
'COMM_TEXT3': 'İlk çalıştırma kontrolü ',
'COMM_TEXT4': 'Kontrol ',
'COMM_TEXT5': 'Açıklama ',
'COMM_Q1_Q': '1. Kurulum….tarafından yapılmıştır ',
'COMM_Q1_A1': 'Atlas Copco ',
'COMM_Q1_A2': 'Müşteri ',
'COMM_Q2_Q': '2. Elektrik bağlantıları …. Tarafından yapılmıştır ',
'COMM_Q2_A1': 'Atlas Copco ',
'COMM_Q2_A2': 'Müşteri ',
'COMM_Q3_Q': '3. Ekipmanda herhangi bir hasar mevcut mudur? ',
'COMM_Q3_A1': 'Evet ',
'COMM_Q3_A2': 'Hayır ',
'COMM_Q3_A3': 'Eğer cevabınız evetse, hasar nerededir ',
'COMM_Q4_Q': '4. Ekipmanda herhangi bir korozyon mevcut mudur? ',
'COMM_Q4_A1': 'Evet ',
'COMM_Q4_A2': 'Hayır ',
'COMM_Q4_A3': 'Eğer cevabınız evetse, hasar nerededir ',
'COMM_Q5_Q': '5.Ortam koşulları nasıldır? ',
'COMM_Q5_A1': 'Temiz ',
'COMM_Q5_A2': 'Tozlu ',
'COMM_Q5_A3': 'Çok Tozlu ',
'COMM_Q6_Q': '6. Kompresör odasında uygun havalandırma mevcut mudur? ',
'COMM_Q6_A1': 'Evet ',
'COMM_Q6_A2': 'Hayır ',
'COMM_Q7_Q': '7. Aynı odada başka kompresörler mevcut mudur? ',
'COMM_Q7_A1': 'Evet ',
'COMM_Q7_A2': 'Hayır ',
'COMM_Q7_A3': 'Eğer cevabınız evetse, hangileridir? ',
'COMM_Q8_Q': '8. Temeli, kurulum sağlam mıdır? ',
'COMM_Q8_A1': 'Evet ',
'COMM_Q8_A2': 'Hayır ',
'COMM_Q9_Q': '9. Giriş ve/veya çıkış kanalları kullanılıyor mu? ',
'COMM_Q9_A1': 'Sadece giriş ',
'COMM_Q9_A2': 'Sadece çıkış ',
'COMM_Q9_A3': 'Hem giriş hem çıkış ',
'COMM_Q10_Q': '10. Grişi havası kalitesi uygun mudur? ',
'COMM_Q10_A1': 'Evet ',
'COMM_Q10_A2': 'Hayır ',
'COMM_Q11_Q': '11. Hava bağlantısı uygun mudur? ',
'COMM_Q11_A1': 'Evet ',
'COMM_Q11_A2': 'Hayır ',
'COMM_Q12_Q': '12. Hava tahliye borusu uygun mudur? ',
'COMM_Q12_A1': 'Evet ',
'COMM_Q12_A2': 'Hayır ',
'COMM_Q13_Q': '13. Hava tankı kurulu mudur? ',
'COMM_Q13_A1': 'Evet ',
'COMM_Q13_A2': 'Hayır ',
'COMM_Q13_A3': 'Hacmi nedir ',
'COMM_Q13_A4': 'kaç litre ',
'COMM_Q14_Q': '14. Kompresörün arkasına takılmış filtreler bulunmakta mıdır? ',
'COMM_Q14_A1': 'Evet ',
'COMM_Q14_A2': 'Hayır ',
'COMM_Q14_A3': 'Eğer cevabınız evetse, hangileridir? ',
'COMM_Q15_Q': '15. Kurutucu kurulu mudur? ',
'COMM_Q15_A1': 'Evet ',
'COMM_Q15_A2': 'Hayır ',
'COMM_Q15_A3': 'Eğer cevabınız evetse, hangileridir? ',
'COMM_Q16_Q': '16. Soğutma havası kalitesi uygun mudur? ',
'COMM_Q16_A1': 'Evet ',
'COMM_Q16_A2': 'Hayır ',
'COMM_Q17_Q': '17. Soğuk su akışı mevcut mudur? ',
'COMM_Q17_A1': 'Evet ',
'COMM_Q17_A2': 'Hayır ',
'COMM_Q17_A3': 'Eğer cevabınız evetse, akışı l/s olarak ne kadardır? ',
'COMM_Q18_Q': '18. Tahliye suyu nereye gitmektedir? ',
'COMM_Q18_A1': 'Yağ/su filtrelerine ',
'COMM_Q18_A2': 'Lağıma ',
'COMM_Q19_Q': '19. Voltaj ',
'COMM_Q20_Q': '20. Frekans ',
'COMM_Q21_Q': '21. Ana motor aşırı yük ayarı ',
'COMM_Q22_Q': '22. Fan motoru aşırı yük ayarı ',
'COMM_Q23_Q': '23. Yük/Yüksüz basıncı ',
'COMM_Q23_A1': 'Bar ',
'COMM_Q24_Q': '24. Müşteriye elektronikon eğitimi ',
'COMM_Q24_A1': 'Evet ',
'COMM_Q24_A2': 'Hayır ',
'COMM_Q25_Q': '25.  ',
'COMM_Q25_A1': 'ek kontroller… ',
'COMM_Q26_Q': '26.  ',
'COMM_Q26_A1': 'ek kontroller… ',
'COMM_Q27_Q': '27.  ',
'COMM_Q27_A1': 'ek kontroller… ',
'COMM_Q28_Q': '28. Ölçüm aracı ',
'COMM_Q29_Q': '29. Seri No ',
'COMM_Q30_Q': '30. Sertifika No '
};
