export var textLiterals = {

  'LANGUAGE': 'FR',
  'VISIT_REPORT': "Rapport d'intervention",
  'COMMISSION_REPORT': 'Rapport de mise en service',
  'LMRA_REPORT': 'Rapport de sécurité',
  'SMARTBOX_REPORT': 'Installations SmartBox',
  'SPM_REPORT': 'Rapport SPM',
  'TIME_CONFIRMATION_REPORT': 'Rapport de confirmation de temps',
  'CUSTOMER_DETAILS': 'Détails du client',
  'CONTACT': 'Contact',
  'REPORT_DATE': 'Date du Rapport ',
  'EQUIPMENT': 'Équipement',
  'RUNNING_HOURS': 'Heures de marche',
  'HOURS': 'heures',
  'SERIAL_NUMBER': 'Numéro de série',
  'LOAD_HOURS': 'Heures de chargement',
  'VISIT_DATE': 'Date de visite',
  'ORDER_NUMBER': 'Numéro de commande',
  'CONTRACT_NUMBER': 'Numéro de contrat',
  'PO_NUMBER': 'Bon de commande',
  'WORK_COMMENTS': "Commentaires sur l'opération ",
  'NEXT_VISIT': 'Prochaine visite',
  'NEXT_RECOMMENDED_SERVICE_1': 'Le prochaine mantenance recommandée  est un "',
  'NEXT_RECOMMENDED_SERVICE_2': " La date d'expiration estimée ",
  'FOLLOWING_WORK_IS': 'Les travaux suivants sont recommandés, vous seriez contacté par notre service commercial',
  'ESTIMATED_WORK_HOUR': 'Heure de travail estimée',
  'TIME_CONFIRMATION': 'Confirmation de temps',
  'DATE': 'Date',
  'SERVICE_ENGINEER': 'Technicien service après vente',
  'ACTIVITY_TYPE': "Type d'activité",
  'HOUR_KM': 'Heure / km',
  'MATERIAL_CONFIRMATION': 'Confirmation matériel',
  'PART_NUMBER': "Numéro d'article",
  'PART_DESCRIPTION': 'Description de la pièce',
  'QUANTITY_UNIT': 'Unité de quantité',
  'WORK_DONE': 'Travail effectué',
  'OPERATIONS': 'Opérations',
  'COMMENTS': 'commentaires',
  'MEASUREMENT_POINTS': 'Points de mesure',
  'COUNTER': 'Compteur',
  'READING_AFTER_SERVICE': "Lecture après l'intervention",
  'BEFORE_SERVICE': "Avant l'intervention",
  'FROM_LAST_VISIT_ON': 'De la dernière visite sur',
  'AUTHORISATION_TO_CARRY': 'Autorisation de réaliser l´intervention avec ou sans obtention d´un N° de commande client',
  'NOTES': 'Remarques',
  'CUSTOMER_WILL_AGREE': "Le client acceptera de fournir à Atlas Copco un numéro de commande valide ou un paiement pour les client non-compte à savoir le temps passé, les déplacements et les pièces utilisées lors de l'intervention en cas de panne au plus tard le jour ouvrable suivant.",
  'CUSTOMER_CONFIRMATION': 'Confirmation du client',
  'SERVICE_ENGINEER_CONFIRMATION': "Confirmation de l'ingénieur de service",
  'ENTER_YOUR_NAME': 'Entrez votre nom',
  'PLEASE_ENTER_YOUR': 'Entrez votre nom ici',
  'SIGNED_BY': 'Signé par',
  'AT': 'à',
  'BEING_DULY_AUTHORISED': '(Etre dûment autorisé à signer au nom du client)',

  'SAFETY_FIRST': "La sécurité d'abord",
  'QUESTION': 'Question',
  'CHECKED': 'Vérifié',

  'COMPANY_GROUP_NAME': 'Atlas Copco Maroc SA',
  'COMPANY_LEGAL_NAME': 'Atlas Copco Maroc SA',
  'VISITORS_ADDRESS': 'Adresse du visiteur',
  'TELEPHONE': 'Tél ',
  'COMPANY_TELEPHONE': '+212 522 63 4000',
  'FOOTER_ADDITIONAL_INFO_1': '2-6 Rue Ibnou Adara El Marrakouchi ',
  'COMPANY_ADDRESS_1': 'Casablanca, Maroc ',
  'VISITOR_ADDRESS_1': 'Boite Postal 20 300',
  'FAX': 'Fax ',
  'COMPANY_FAX': '+212  522 600522 ',
  'FOOTER_ADDITIONAL_INFO_2': '',
  'COMPANY_ADDRESS_2': '',
  'VISITOR_ADDRESS_2': '',
  'COMPANY_URL': 'Www.atlascopco.ma',
  'FOOTER_ADDITIONAL_INFO_3': 'Mersis No: 0102004456300016',
  'WORKER_DETAIL': 'Détail des intervenants ',
  'WORK_CENTER': 'Centre de travail',
  'SEARCH_OPTIONS': 'Options de recherche',
  'DATE_FROM': 'De',
  'DATE_TO': 'À',
  'TOTAL': 'Total',
  'WEEK': 'La semaine',
  'COMM_TEXT1' : "Procédure de Mise en Service ",
  'COMM_TEXT2' : "La mise en service d'un compresseur revêt une importance particulière. Une mise en service correcte est la première étape de la construction de l'historique de l'équipement. L'historique de l'équipement est essentiel pour un bon suivi. Lors de la mise en service, l'ingénieur de maintenance ( technicien)enregistrera les lectures de service initiales et d'autres données de fonctionnement de l'équipement. Toutes les températures, pressions, tensions, Intensité de courant, etc. doivent être correctement enregistrés, en utilisant les instruments (Capteurs) et jauges de service appropriés. Les données de service dans le rapport de mise en service constitueront une source de référence importante à un stade ultérieur. Vous y ferez référence lors de la manipulation, par exemple lors de la discussion de tout problème de service. Si les relevés de service n'ont pas été enregistrés lors de la mise en service, la comparaison à un stade ultérieur peut devenir considérablement plus difficile. ",
  'COMM_TEXT3' : "Contrôle de la mise en service  ",
  'COMM_TEXT4' : "Vérifier ",
  'COMM_TEXT5' : "Commentaires ",
  'COMM_Q1_Q' : "1. Installation réalisée par ",
  'COMM_Q1_A1' : "Atlas Copco ",
  'COMM_Q1_A2' : "Client ",
  'COMM_Q2_Q' : "2. Connection électrique réalisée par ",
  'COMM_Q2_A1' : "Atlas Copco ",
  'COMM_Q2_A2' : "Client ",
  'COMM_Q3_Q' : "3. Y-t-il des dommages au niveau de l'équipement ",
  'COMM_Q3_A1' : "Oui ",
  'COMM_Q3_A2' : "Non ",
  'COMM_Q3_A3' : "Si oui, où… ",
  'COMM_Q4_Q' : "4. Y-t-il des signes de corrosion sur l'équipement ",
  'COMM_Q4_A1' : "Oui ",
  'COMM_Q4_A2' : "Non ",
  'COMM_Q4_A3' : "Si oui, où… ",
  'COMM_Q5_Q' : "5. Condition environmentale ",
  'COMM_Q5_A1' : "Propre ",
  'COMM_Q5_A2' : "Sale ",
  'COMM_Q5_A3' : "Très Sale ",
  'COMM_Q6_Q' : "6. La salle des compresseur est-elle aérée correctement ",
  'COMM_Q6_A1' : "Oui ",
  'COMM_Q6_A2' : "Non ",
  'COMM_Q7_Q' : "7. Y-t-il d'autres compresseurs dans la même salle ",
  'COMM_Q7_A1' : "Oui ",
  'COMM_Q7_A2' : "Non ",
  'COMM_Q7_A3' : "Si oui, … ",
  'COMM_Q8_Q' : "8. Fondation OK ",
  'COMM_Q8_A1' : "Oui ",
  'COMM_Q8_A2' : "Non ",
  'COMM_Q9_Q' : "9. Conduites à l'entrée et/ou la sortie sont elles utlisées ",
  'COMM_Q9_A1' : "Uniquement à l'entrée ",
  'COMM_Q9_A2' : "Uniquement à la sortie ",
  'COMM_Q9_A3' : "Tout les deux entrée/sortie ",
  'COMM_Q10_Q' : "10. Qualité d'air d'entrée OK ",
  'COMM_Q10_A1' : "Oui ",
  'COMM_Q10_A2' : "Non ",
  'COMM_Q11_Q' : "11. Collecteur d'air OK ",
  'COMM_Q11_A1' : "Oui ",
  'COMM_Q11_A2' : "Non ",
  'COMM_Q12_Q' : "12. Conduite de refoulement d'air OK ",
  'COMM_Q12_A1' : "Oui ",
  'COMM_Q12_A2' : "Non ",
  'COMM_Q13_Q' : "13. Reservoir d'air installé ",
  'COMM_Q13_A1' : "Oui ",
  'COMM_Q13_A2' : "Non ",
  'COMM_Q13_A3' : "Volume ",
  'COMM_Q13_A4' : "l ",
  'COMM_Q14_Q' : "14. Filtre(s) installé après le compresseur ",
  'COMM_Q14_A1' : "Oui ",
  'COMM_Q14_A2' : "Non ",
  'COMM_Q14_A3' : "Si oui, … ",
  'COMM_Q15_Q' : "15. Sécheur installé ",
  'COMM_Q15_A1' : "Oui ",
  'COMM_Q15_A2' : "Non ",
  'COMM_Q15_A3' : "Si oui, … ",
  'COMM_Q16_Q' : "16. Qualité de l'eau de refroidissement OK ",
  'COMM_Q16_A1' : "Oui ",
  'COMM_Q16_A2' : "Non ",
  'COMM_Q17_Q' : "17. Débit d'eau de refroidissement l/s ",
  'COMM_Q17_A1' : "Oui ",
  'COMM_Q17_A2' : "Non ",
  'COMM_Q17_A3' : "l/s ",
  'COMM_Q18_Q' : "18. Eau de purge par vers ",
  'COMM_Q18_A1' : "Huile/eau filtre ",
  'COMM_Q18_A2' : "Egout ",
  'COMM_Q19_Q' : "19. Voltage ",
  'COMM_Q20_Q' : "20. Fréquence ",
  'COMM_Q21_Q' : "21. Réglage de surcharge du moteur principal ",
  'COMM_Q22_Q' : "22. Réglage de surcharge des moto(s) ventilateur ",
  'COMM_Q23_Q' : "23. Pression Charge/Décharge ",
  'COMM_Q23_A1' : "Bar ",
  'COMM_Q24_Q' : "24. Instruction de l'usage du Elektronikon en faveur du client ",
  'COMM_Q24_A1' : "Oui ",
  'COMM_Q24_A2' : "Non ",
  'COMM_Q25_Q' : "25.  ",
  'COMM_Q25_A1' : "Vérification additionnelle... ",
  'COMM_Q26_Q' : "26.  ",
  'COMM_Q26_A1' : "Vérification additionnelle… ",
  'COMM_Q27_Q' : "27.  ",
  'COMM_Q27_A1' : "Vérification additionnelle… ",
  'COMM_Q28_Q' : "28. Instrument de mesure ",
  'COMM_Q29_Q' : "29. Numéro de Série ",
  'COMM_Q30_Q' : "30. Numéro de Certificat ",



};
