export var textLiterals = {
  'VISIT_REPORT': 'Reporte de Visita',
  'COMMISSION_REPORT': 'Reporte de Puesta en Marcha',
  'LMRA_REPORT': 'Lista de Chequeo de Seguridad',
  'SMARTBOX_REPORT': 'Reporte Instalación Smartbox',
  'SPM_REPORT': 'Reporte SPM',
  'TIME_CONFIRMATION_REPORT': 'Reporte de Confirmación de Tiempo',
  'CUSTOMER_DETAILS': 'Detalles del Cliente',
  'CONTACT': 'Contacto',
  'REPORT_DATE': 'Fecha de Reporte',
  'EQUIPMENT': 'Equipo',
  'RUNNING_HOURS': 'Horas de Marcha',
  'HOURS': 'Horas ',
  'SERIAL_NUMBER': 'Número de Serie',
  'LOAD_HOURS': 'Horas en Carga',
  'VISIT_DATE': 'Fecha de Visita',
  'ORDER_NUMBER': 'Número de Orden',
  'CONTRACT_NUMBER': 'Número de Contrato',
  'PO_NUMBER': 'Número de Orden de Compra',
  'WORK_COMMENTS': 'Comentarios',
  'NEXT_VISIT': 'Próxima Visita',
  'NEXT_RECOMMENDED_SERVICE_1': 'El próximo servicio recomendado es "',
  'NEXT_RECOMMENDED_SERVICE_2': 'Fecha estimada requerida "',
  'FOLLOWING_WORK_IS': 'Se recomienda el siguiente servicio, para el cual nuestro Representante de Ventas se comunicará próximamente.',
  'ESTIMATED_WORK_HOUR': 'Horas estimadas de trabajo',
  'TIME_CONFIRMATION': 'Confirmación de Tiempo',
  'DATE': 'Fecha',
  'SERVICE_ENGINEER': 'Técnico de Servicio',
  'ACTIVITY_TYPE': 'Tipo de Actividad',
  'HOUR_KM': 'Horas/Kilómetro',
  'MATERIAL_CONFIRMATION': 'Confirmación de repuestos',
  'PART_NUMBER': 'Número de Parte',
  'PART_DESCRIPTION': 'Descripción',
  'QUANTITY_UNIT': 'Unidades',
  'WORK_DONE': 'Trabajo realizado',
  'OPERATIONS': 'Operaciones',
  'COMMENTS': 'Comentarios',
  'MEASUREMENT_POINTS': 'Puntos de medición',
  'COUNTER': 'Contador',
  'READING_AFTER_SERVICE': 'Lectura despues del servicio',
  'BEFORE_SERVICE': 'Antes del servicio',
  'FROM_LAST_VISIT_ON': 'Desde la última visita en',
  'AUTHORISATION_TO_CARRY': 'Autorización para realizar un trabajo con/sin una Orden de Compra',
  'NOTES': 'Notas',
  'CUSTOMER_WILL_AGREE': 'El Cliente acepta proveer a Atlas Copco una orden de compra válida o pago por cargos de tiempo de trabajo, desplazamiento y repuestos usados durante la atención de emergencia, tan pronto como sea posible.',
  'CUSTOMER_CONFIRMATION': 'Confirmación del Cliente',
  'SERVICE_ENGINEER_CONFIRMATION': 'Confirmación del Técnico de Servicio',
  'ENTER_YOUR_NAME': 'Ingrese su nombre',
  'PLEASE_ENTER_YOUR': 'Por favor ingrese su nombre aquí',
  'SIGNED_BY': 'Firmado por ',
  'AT': 'el',
  'BEING_DULY_AUTHORISED': '(Siendo debidamente autorizado a firmar en representación del Cliente)',
  'SAFETY_FIRST': 'Primero la Seguridad',
  'QUESTION': 'Detalles del Trabajador',
  'CHECKED': 'Verificado',
  'COMPANY_GROUP_NAME': 'Atlas Copco S.A.E. - División Compresores',

  'COMPANY_LEGAL_NAME': 'Avda Jose Garate 3',

  'COMPANY_ADDRESS_1': 'Polígono Industrial Coslada, Apartado 43',

  'COMPANY_ADDRESS_2': '28823 Coslada (Madrid)',

  'VISITORS_ADDRESS': 'Telefono: +34 916 279 100',

  'VISITOR_ADDRESS_1': 'Email: ac.spain@es.atlascopco.com',

  'VISITOR_ADDRESS_2': 'Sociedad Unipersonal.Reg. Mer.',

  'FOOTER_CENTER_LINE1': 'Madrid -T 223 F.36 -hoja 6341 - Inscrip. 1º',

  'COMPANY_FAX': 'NIF: A28000057',

  'COMPANY_URL': 'Cod.Comunitario ESA28000057',

  'FOOTER_ADDITIONAL_INFO_1': 'Banco Deutsche Bank',

  'FOOTER_ADDITIONAL_INFO_2': 'IBAN: ES43 0019 0030 6540 1020 6281',

  'FOOTER_ADDITIONAL_INFO_3': 'SWIFT: DEUTESBBXXX',
  'WORKER_DETAIL': 'Detalles del Trabajador',
  'WORK_CENTER': 'Centro de Trabajo',
  'SEARCH_OPTIONS': 'Opciones de búsqueda',
  'DATE_FROM': 'Desde',
  'DATE_TO': 'Hasta',
  'TOTAL': 'Total',
  'WEEK': 'Semana'
};
