export var textLiterals = {
  'VISIT_REPORT': ' Relatório de Assistência',
  'COMMISSION_REPORT': 'Relatório de Comissionamento',
  'LMRA_REPORT': 'Relatório de Segurança - Safety First',
  'SMARTBOX_REPORT': 'Instalações SmartBox',
  'SPM_REPORT': 'Relatório SPM',
  'TIME_CONFIRMATION_REPORT': 'Relatório de Confirmação de Tempos',
  'CUSTOMER_DETAILS': 'Detalhes do Cliente',
  'CONTACT': 'Contacto',
  'REPORT_DATE': 'Data do Relatório',
  'EQUIPMENT': 'Equipamento',
  'RUNNING_HOURS': 'Horas Totais',
  'HOURS': 'Horas',
  'SERIAL_NUMBER': 'Nº. de Série',
  'LOAD_HOURS': 'Horas em Carga',
  'VISIT_DATE': 'Data da Visita',
  'ORDER_NUMBER': 'Nº. de Obra',
  'CONTRACT_NUMBER': 'Nº. do Contrato',
  'PO_NUMBER': 'Nº. de Encomenda',
  'WORK_COMMENTS': 'Relatório',
  'NEXT_VISIT': 'Próxima Visita',
  'NEXT_RECOMMENDED_SERVICE_1': 'Próxima Intervenção Recomendada:“',
  'NEXT_RECOMMENDED_SERVICE_2': '” Data prevista',
  'FOLLOWING_WORK_IS': 'Recomenda-se a seguinte intervenção. Os nossos serviços comerciais irão contactá-lo(a) brevemente',
  'ESTIMATED_WORK_HOUR': 'Horas de trabalho estimadas',
  'TIME_CONFIRMATION': 'Registo de Horas',
  'DATE': 'Data',
  'SERVICE_ENGINEER': 'Técnico',
  'ACTIVITY_TYPE': 'Tipo de serviço',
  'HOUR_KM': 'Hora/Km',
  'MATERIAL_CONFIRMATION': 'Material Aplicado',
  'PART_NUMBER': 'Referência',
  'PART_DESCRIPTION': 'Descrição',
  'QUANTITY_UNIT': 'Quantidade',
  'WORK_DONE': 'Lista de Actividades',
  'OPERATIONS': 'Operações',
  'COMMENTS': 'Comentários',
  'MEASUREMENT_POINTS': 'Pontos de Medida',
  'COUNTER': 'Leituras',
  'READING_AFTER_SERVICE': 'Após a Assistência',
  'BEFORE_SERVICE': 'Antes da Assistência',
  'FROM_LAST_VISIT_ON': 'Última Visita',
  'AUTHORISATION_TO_CARRY': 'CONFIRMAÇÃO DA ASSISTÊNCIA EFECTUADA',
  'NOTES': 'Notas',
  'CUSTOMER_WILL_AGREE': 'O cliente confirma que os serviços do presente relatório foram executados. Caso seja necessário n.º encomenda válido por favor endereçar o mesmo para os nossos Serviços de Assistência Técnica.',
  'CUSTOMER_CONFIRMATION': 'Confirmação do Cliente',
  'SERVICE_ENGINEER_CONFIRMATION': 'Confirmação do Técnico de Assistência',
  'ENTER_YOUR_NAME': 'Digite o seu nome',
  'PLEASE_ENTER_YOUR': 'Por favor insira aqui o seu nome',
  'SIGNED_BY': 'Assinado por',
  'AT': 'em',
  'BEING_DULY_AUTHORISED': '(Tendo sido devidamente autorizado a assinar em substituição do cliente)',

  'SAFETY_FIRST': 'Safety First',
  'QUESTION': 'Questões',
  'CHECKED': 'Verificado',

  'COMPANY_GROUP_NAME': 'Divisão de Compressores',
  'COMPANY_LEGAL_NAME': 'Soc. Atlas Cocpo de Portugal, Lda.',
  'VISITORS_ADDRESS': 'Sede',
  'TELEPHONE': 'Telf',
  'COMPANY_TELEPHONE': '+351 214168500',
  'FOOTER_ADDITIONAL_INFO_1': 'Banco BNP PAribas',
  'COMPANY_ADDRESS_1': 'Lagoas Park, Edifício 15, Piso 0',
  'VISITOR_ADDRESS_1': '2740-265 Porto Salvo',
  'FAX': 'Fax',
  'COMPANY_FAX': '+351 214171913',
  'FOOTER_ADDITIONAL_INFO_2': 'NIB 500254265',
  'COMPANY_ADDRESS_2': '2740-265 Porto Salvo',
  'VISITOR_ADDRESS_2': 'Portugal',
  'COMPANY_URL': 'www.atlascopco.com',
  'FOOTER_ADDITIONAL_INFO_3': '',
  'WORKER_DETAIL': 'Detalhes do trabalhador',
  'WORK_CENTER': 'Centro de Assistência',
  'SEARCH_OPTIONS': 'Procurar Opções',
  'DATE_FROM': 'De',
  'DATE_TO': 'Para'
};
