export var textLiterals = {
  'LANGUAGE': 'RU',
  'VISIT_REPORT': 'Сервисный отчет',
  'COMMISSION_REPORT': 'Протокол ввода в эксплуатацию',
  'LMRA_REPORT': 'Отчет по технике безопасности',
  'SMARTBOX_REPORT': 'Наличие SmartBox',
  'SPM_REPORT': 'Отчет SPM',
  'TIME_CONFIRMATION_REPORT': 'Табель учета времени',
  'CUSTOMER_DETAILS': 'Информация по заказчику',
  'CONTACT': 'Контакты',
  'REPORT_DATE': 'Дата отчета',
  'EQUIPMENT': 'Оборудование',
  'RUNNING_HOURS': 'Наработка',
  'HOURS': 'часы',
  'SERIAL_NUMBER': 'Серийный номер',
  'LOAD_HOURS': 'Часы в загрузке',
  'VISIT_DATE': 'Дата визита',
  'ORDER_NUMBER': 'Номер Сервисного Отчета',
  'CONTRACT_NUMBER': 'Контракт №',
  'PO_NUMBER': 'РО №',
  'WORK_COMMENTS': 'Комментарии',
  'NEXT_VISIT': 'Следующий визит',
  'NEXT_RECOMMENDED_SERVICE_1': 'Следующее рекомендуемое обслуживание "',
  'NEXT_RECOMMENDED_SERVICE_2': '" планируемая дата проведения работ',
  'FOLLOWING_WORK_IS': 'Рекомендуется следующий ремонт, в ближайшее время с Вами свяжется ответственный специалист',
  'ESTIMATED_WORK_HOUR': 'Планируемое время работ',
  'TIME_CONFIRMATION': 'Подтверждение времени',
  'DATE': 'Дата',
  'SERVICE_ENGINEER': 'Сервисный инженер',
  'ACTIVITY_TYPE': 'Вид работ',
  'HOUR_KM': 'Час/км',
  'MATERIAL_CONFIRMATION': 'Используемые материалы',
  'PART_NUMBER': 'Каталожный номер',
  'PART_DESCRIPTION': 'Описание материала',
  'QUANTITY_UNIT': 'Количество (юнитов)',
  'WORK_DONE': 'Работа выполнена',
  'OPERATIONS': 'Инженерная',
  'COMMENTS': 'Комментарии',
  'MEASUREMENT_POINTS': 'Лист измерений',
  'COUNTER': 'Счетчик',
  'READING_AFTER_SERVICE': 'Измерения после сервиса',
  'BEFORE_SERVICE': 'Измерения до сервиса',
  'FROM_LAST_VISIT_ON': 'С последнего визита по',
  'AUTHORISATION_TO_CARRY': 'ДОПУСК К РАБОТАМ С/БЕЗ НАРЯДА NO.',
  'NOTES': 'Заметки',
  'CUSTOMER_WILL_AGREE': 'Заказчик соглашается предоставить ТОО Атлас Копко Эйрпауэр Центральная Азия достоверную информацию',
  'CUSTOMER_CONFIRMATION': 'Подпись Заказчика',
  'SERVICE_ENGINEER_CONFIRMATION': 'Подпись Сервисного Инженера',
  'ENTER_YOUR_NAME': 'Заполните свое имя',
  'PLEASE_ENTER_YOUR': 'Заполните пожалуйста свое имя в данное поле',
  'SIGNED_BY': 'Подписан',
  'AT': 'лицом',
  'BEING_DULY_AUTHORISED': '(являющимся уполномоченным со стороны Заказчика)',

  'SAFETY_FIRST': 'ТБиОТ',
  'QUESTION': 'Вопрос',
  'CHECKED': 'Проверено/Подтверждено',

  'COMPANY_GROUP_NAME': 'Атлас Копко Эйрпауэр Центральная Азия',
  'COMPANY_LEGAL_NAME': '',
  'VISITORS_ADDRESS': 'Поставщик/адрес',
  'TELEPHONE': 'Тел',
  'COMPANY_TELEPHONE': '8 727 313 20 12',
  'FOOTER_ADDITIONAL_INFO_1': '',
  'COMPANY_ADDRESS_1': 'Бегалина 148/14',
  'VISITOR_ADDRESS_1': '050010',
  'FAX': '',
  'COMPANY_FAX': '',
  'FOOTER_ADDITIONAL_INFO_2': '',
  'COMPANY_ADDRESS_2': '050010 Алматы',
  'VISITOR_ADDRESS_2': '050010 Алматы',
  'COMPANY_URL': 'www.atlascopco.kz',
  'FOOTER_ADDITIONAL_INFO_3': 'Алматы, Казахстан',
  'WORKER_DETAIL': 'Информация по инженеру',
  'WORK_CENTER': 'Сервисный центр',
  'SEARCH_OPTIONS': 'Параметры поиска',
  'DATE_FROM': 'Из',
  'DATE_TO': 'В',
  'TOTAL': 'Всего',
  'WEEK': 'Неделя'
};
