export var textLiterals = {
  'VISIT_REPORT': 'Visit Report',
  'COMMISSION_REPORT': 'Commissioning Report',
  'LMRA_REPORT': 'Safety First Report',
  'SMARTBOX_REPORT': 'SmartBox Installations',
  'SPM_REPORT': 'SPM Report',
  'TIME_CONFIRMATION_REPORT': 'Time Confirmation Report',
  'CUSTOMER_DETAILS': 'Customer Details',
  'CONTACT': 'Contact',
  'REPORT_DATE': 'Report date',
  'EQUIPMENT': 'Equipment',
  'RUNNING_HOURS': 'Running Hours',
  'HOURS': 'hours',
  'SERIAL_NUMBER': 'Serial Number',
  'LOAD_HOURS': 'Load Hours',
  'VISIT_DATE': 'Visit date',
  'ORDER_NUMBER': 'Order Number',
  'CONTRACT_NUMBER': 'Contract Number',
  'PO_NUMBER': 'PO number',
  'WORK_COMMENTS': 'Work Comments',
  'NEXT_VISIT': 'Next Visit',
  'NEXT_RECOMMENDED_SERVICE_1': 'Next recommended service is a “',
  'NEXT_RECOMMENDED_SERVICE_2': '” estimated due date',
  'FOLLOWING_WORK_IS': 'Following work is recommended, our service sales will contact you',
  'ESTIMATED_WORK_HOUR': 'Estimated work hour',
  'TIME_CONFIRMATION': 'Time Confirmation',
  'DATE': 'Date',
  'SERVICE_ENGINEER': 'Service Engineer',
  'ACTIVITY_TYPE': 'Activity Type',
  'HOUR_KM': 'Hour/km',
  'MATERIAL_CONFIRMATION': 'Material Confirmation',
  'PART_NUMBER': 'Part Number',
  'PART_DESCRIPTION': 'Part Description',
  'QUANTITY_UNIT': 'Quantity unit',
  'WORK_DONE': 'Work Done',
  'OPERATIONS': 'Operations',
  'COMMENTS': 'Comments',
  'MEASUREMENT_POINTS': 'Measurement Points',
  'COUNTER': 'Counter',
  'READING_AFTER_SERVICE': 'Reading after service',
  'BEFORE_SERVICE': 'Before service',
  'FROM_LAST_VISIT_ON': 'From last visit on',
  'AUTHORISATION_TO_CARRY': 'AUTHORISATION TO CARRY OUT WORK WITH/WITHOUT AN ORDER NO.',
  'NOTES': 'Notes',
  'CUSTOMER_WILL_AGREE': 'Customer will agree to supply Atlas Copco with a valid order number or payment for non-account holders for actual time spend, travelling and parts used during the breakdown intervention by next working day.',
  'CUSTOMER_CONFIRMATION': 'Customer Confirmation',
  'SERVICE_ENGINEER_CONFIRMATION': 'Service Engineer Confirmation',
  'ENTER_YOUR_NAME': 'Enter your name',
  'PLEASE_ENTER_YOUR': 'Please enter your name here',
  'SIGNED_BY': 'Signed by',
  'AT': 'at',
  'BEING_DULY_AUTHORISED': '(Being duly authorised to sign on behalf of the customer)',

  'SAFETY_FIRST': 'Safety First',
  'QUESTION': 'Question',
  'CHECKED': 'Checked',

  'COMPANY_GROUP_NAME': '아트라스콥코 제조한국㈜',
  'COMPANY_LEGAL_NAME': '경기도 용인시 처인구 양지면 주북로',
  'VISITORS_ADDRESS': 'Hotline 24/7 : 1577-9154',
  'TELEPHONE': 'Phone: ',
  'COMPANY_TELEPHONE': '031 322 7193',
  'FOOTER_ADDITIONAL_INFO_1': '',
  'COMPANY_ADDRESS_1': '173번길 22-10 (우) 449-822',
  'VISITOR_ADDRESS_1': '031 322 7193',
  'FAX': 'Fax: ',
  'COMPANY_FAX': '031 322 7195',
  'FOOTER_ADDITIONAL_INFO_2': '',
  'COMPANY_ADDRESS_2': '*본 서비스에 대한 고객 설문 이메일이 발송 될 예정이오니, 바쁘시더라도 성실한 응답 부탁드리겠습니다. 감사합니다',
  'VISITOR_ADDRESS_2': '',
  'COMPANY_URL': '',
  'FOOTER_ADDITIONAL_INFO_3': '',
  'WORKER_DETAIL': 'Worker Detail',
  'WORK_CENTER': 'Work Center',
  'SEARCH_OPTIONS': 'Search Options',
  'DATE_FROM': 'From',
  'DATE_TO': 'To',
  'TOTAL': 'Total',
  'WEEK': 'Week'
};
