export var textLiterals = {
  'VISIT_REPORT': 'Отчет за посещение',
  'CUSTOMER_DETAILS': 'Детайли на клиента',
  'CONTACT': 'Лице за контакт',
  'REPORT_DATE': 'Дата на отчет',
  'EQUIPMENT': 'Оборудване',
  'RUNNING_HOURS': 'Работни часове',
  'HOURS': 'часове',
  'SERIAL_NUMBER': 'Сериен номер',
  'LOAD_HOURS': 'Часове под товар',
  'VISIT_DATE': 'Дата на посещение',
  'ORDER_NUMBER': 'Номер на поръчка',
  'CONTRACT_NUMBER': 'Номер на договор',
  'PO_NUMBER': 'PO номер',
  'WORK_COMMENTS': 'Коментари за работата',
  'NEXT_VISIT': 'Следващо посещение',
  'NEXT_RECOMMENDED_SERVICE_1': ' Следващо обслужване тип: "',
  'NEXT_RECOMMENDED_SERVICE_2': '" Очаквана дата на следващо посещение: ',
  'FOLLOWING_WORK_IS': 'Служител на Атлас Копко предвартелно ще свърже с вас за изготвяне на оферта',
  'ESTIMATED_WORK_HOUR': 'Прогнозни работни часове',
  'TIME_CONFIRMATION': 'Потвърждение на работни часове',
  'DATE': 'Дата',
  'SERVICE_ENGINEER': 'Сервизен инженер',
  'ACTIVITY_TYPE': 'Вид дейност',
  'HOUR_KM': 'час',
  'MATERIAL_CONFIRMATION': 'Потвърждение на вложени материали',
  'PART_NUMBER': 'Номер на част',
  'PART_DESCRIPTION': 'Описание на частта',
  'QUANTITY_UNIT': 'количество',
  'WORK_DONE': 'Свършена работа',
  'OPERATIONS': 'Операции',
  'COMMENTS': 'Коментари',
  'MEASUREMENT_POINTS': 'Точки на измерване',
  'COUNTER': 'Параметър',
  'READING_AFTER_SERVICE': 'Стойност след сервиза',
  'BEFORE_SERVICE': 'Стойност преди сервиза',
  'FROM_LAST_VISIT_ON': 'От последното посещение насам',
  'AUTHORISATION_TO_CARRY': 'Потвърждение за извършена работа с/без поръчка №',
  'NOTES': 'Бележки',
  'CUSTOMER_WILL_AGREE': 'Клиентът се задължава да предостави на Атлас Копко всички документи (поръчка №, възлагателно писмо или друго), необходими за отчитане на извършените допълнителни недоговорени дейности, в рамките на 3 работни дни.',
  'CUSTOMER_CONFIRMATION': 'Потвърждение от клиента',
  'SERVICE_ENGINEER_CONFIRMATION': 'Потвърждение от сервизния инженер',
  'SIGNED_BY': 'Подписано от',
  'ENTER_YOUR_NAME': 'Моля, въведете Вашето име',
  'AT': '',
  'BEING_DULY_AUTHORISED': '(Представител на клиента)',
  'COMPANY_GROUP_NAME': 'Атлас Копко България ЕООД',
  'COMPANY_LEGAL_NAME': 'Атлас Копко България ЕООД',
  'COMPANY_ADDRESS_1': 'бул. Искърско шосе No 7, сгр. 3',
  'COMPANY_ADDRESS_2': '1528 София',
  'VISITORS_ADDRESS': '+359 (0)2 447 26 91',
  'VISITOR_ADDRESS_1': '',
  'VISITOR_ADDRESS_2': '',
  'FOOTER_CENTER_LINE1': 'compressor.service@bg.atlascopco.com',
  'TELEPHONE': 'тел.',
  'FAX': 'факс',
  'COMPANY_FAX': '',
  'COMPANY_URL': 'https://www.atlascopco.com/bg-bg',
  'FOOTER_ADDITIONAL_INFO_1': 'Банка: СИТИБАНК ЕВРОПА АД - Клон България',
  'FOOTER_ADDITIONAL_INFO_2': 'Банкова сметка в лева: IBAN:BG34 CITI 9250 1000 1120 01',
  'FOOTER_ADDITIONAL_INFO_3': 'BIC: CITIBGSF',
  'FOOTER_ADDITIONAL_INFO_4': '',
	'SAFETY_FIRST': 'Безопасността на първо място',
	'QUESTION': 'Въпрос',
	'CHECKED': 'Проверено',
  'WORKER_DETAIL': 'Worker Detail',
  'WORK_CENTER': 'Work Center',
  'SEARCH_OPTIONS': 'Search Options',
  'DATE_FROM': 'From',
  'DATE_TO': 'To',
  'TOTAL': 'Total',
  'WEEK': 'Week'
};
