export var textLiterals = {
  'VISIT_REPORT': ' Relatório de Assistência',
  'COMMISSION_REPORT': 'Relatório de Comissionamento',
  'LMRA_REPORT': 'Relatório de Segurança- Safety First',
  'SMARTBOX_REPORT': 'Instlações SmartBox',
  'SPM_REPORT': 'Relatório SPM',
  'TIME_CONFIRMATION_REPORT': 'Relatório de Confirmação de Tempos',
  'CUSTOMER_DETAILS': 'Detalhes do Cliente',
  'CONTACT': 'Contacto',
  'REPORT_DATE': 'Data do Relatório',
  'EQUIPMENT': 'Equipmento',
  'RUNNING_HOURS': 'Horas de Funcionamento',
  'HOURS': 'horas',
  'SERIAL_NUMBER': 'No. de Série',
  'LOAD_HOURS': 'Horas em Carga',
  'VISIT_DATE': 'Data da Visita',
  'ORDER_NUMBER': 'No. de Obra',
 'CONTRACT_NUMBER': 'No. do Contrato',
  'PO_NUMBER': 'No. de Encomenda',
  'WORK_COMMENTS': 'Comentários da Obra',
  'NEXT_VISIT': 'Próxima Visita',
  'NEXT_RECOMMENDED_SERVICE_1': 'Próxima intervenção recomendada:“',
  'NEXT_RECOMMENDED_SERVICE_2': '” Data prevista',
  'FOLLOWING_WORK_IS': 'Recomenda-se a intervenção seguinte, os nossos serviços comerciais irão contactá-lo(a)',
  'ESTIMATED_WORK_HOUR': 'Horas de trabalho estimadas',
  'TIME_CONFIRMATION': 'Confirmação de tempo',
  'DATE': 'Data',
  'SERVICE_ENGINEER': 'Técnico de Assistência',
  'ACTIVITY_TYPE': 'Tipo de Atividade',
  'HOUR_KM': 'Hora/km',
  'MATERIAL_CONFIRMATION': 'Confirmação de material',
  'PART_NUMBER': 'Referência',
  'PART_DESCRIPTION': 'Descrição da peça',
  'QUANTITY_UNIT': 'Quantidade',
  'WORK_DONE': 'Trabalho efectuado',
  'OPERATIONS': 'Operações',
  'COMMENTS': 'Comentários',
  'MEASUREMENT_POINTS': 'Pontos de Medida',
  'COUNTER': 'Contador',
  'READING_AFTER_SERVICE': 'Leitura após a assistência',
  'BEFORE_SERVICE': 'Anates da Assistência',
  'FROM_LAST_VISIT_ON': 'Da visita anterior em',
  'AUTHORISATION_TO_CARRY': 'AUTORIZAÇÃO DE TRABALHO PARA EXECUÇÃO DE ASSISTÊNCIA SEM/COM NO. DE ENCOMENDA',
  'NOTES': 'Notas',
  'CUSTOMER_WILL_AGREE': 'O cliente fornecerá à Atlas Copco um no. de encomenda válido ou pagamento de outros titulares de conta, para a mão de obra, custos de deslocaçãoe peças utilizados actualmente, em situação de paragem por avaria e outras ocorridas nos dias de trabalho seguintes.',
  'CUSTOMER_CONFIRMATION': 'Confirmação do Clienten',
  'SERVICE_ENGINEER_CONFIRMATION': 'Confirmação do Técnico de Assistência',
  'ENTER_YOUR_NAME': 'Digite o seu nome',
  'PLEASE_ENTER_YOUR': 'Por favor insira aqui o seu nome',
  'SIGNED_BY': 'Assinado por',
  'AT': 'em',
  'BEING_DULY_AUTHORISED': '(Tendo sido devidamente autorizado a assinar em substituição do cliente)',

  'SAFETY_FIRST': 'Safety First',
  'QUESTION': 'Questão',
  'CHECKED': 'Verificado',

  'COMPANY_GROUP_NAME': 'Divisão de Compressores',
  'COMPANY_LEGAL_NAME': 'Soc. Atlas Cocp de Portugal,Lda.',
  'VISITORS_ADDRESS': 'Visitante\' endereço',
  'TELEPHONE': 'Tel +351 214168500',
  'COMPANY_TELEPHONE': '+351 214168500',
  'FOOTER_ADDITIONAL_INFO_1': 'Banco BNP Paribas',
  'COMPANY_ADDRESS_1': 'Lagoas Park, Edifício 15, Piso 0',
  'VISITOR_ADDRESS_1': '2740-265 Porto Salvo',
  'FAX': 'Fax',
  'COMPANY_FAX': '+351 214171913',
  'FOOTER_ADDITIONAL_INFO_2': 'NIB 500254265',
  'COMPANY_ADDRESS_2': '',
  'VISITOR_ADDRESS_2': 'Portugal',
  'COMPANY_URL': 'www.atlascopco.com',
  'FOOTER_ADDITIONAL_INFO_3': '',
  'WORKER_DETAIL': 'Detalhes do trabalhador',
  'WORK_CENTER': 'Centro de Assistência',
  'SEARCH_OPTIONS': 'Procurar Opções',
  'DATE_FROM': 'De',
  'DATE_TO': 'Para',
  'TOTAL': 'Total',
  'WEEK': 'Semana'
};
