export var textLiterals = {
  'LANGUAGE': 'FR',
 'VISIT_REPORT': "Rapport d'intervention",
  'CUSTOMER_DETAILS': 'Client',
  'CONTACT': 'Contact',
  'REPORT_DATE': 'Date du rapport',
  'EQUIPMENT': 'Equipement',
  'RUNNING_HOURS': 'Heures totales',
  'HOURS': 'Heures',
  'SERIAL_NUMBER': 'Numéro de série',
  'LOAD_HOURS': 'Heures en charges',
  'VISIT_DATE': "Date d'intervention",
  'ORDER_NUMBER': 'N° de rapport',
  'ORDER_DESCRIPTION': 'Description de la visite',
  'CONTRACT_NUMBER': 'N° de contrat',
  'PO_NUMBER': 'N° de commande client',
  'WORK_COMMENTS': 'Commentaires',
  'NEXT_VISIT': 'Prochaine visite de maintenance',
  'NEXT_RECOMMENDED_SERVICE_1': 'prochaine intervention de maintenance préconisé',
  'NEXT_RECOMMENDED_SERVICE_2': 'prochaine intervention de maintenance préconisé',
  'FOLLOWING_WORK_IS': "nous préconisons l'intervention suivante : ",
  'ESTIMATED_WORK_HOUR': 'Heures estimées',
  'TIME_CONFIRMATION': 'Heures réalisées',
  'DATE': 'Date',
  'SERVICE_ENGINEER': 'Technicien',
  'ACTIVITY_TYPE': 'Code activité',
  'HOUR_KM': 'Heures/Km',
  'MATERIAL_CONFIRMATION': 'Pièces utilisées',
  'PART_NUMBER': 'Référence',
  'PART_DESCRIPTION': 'Description',
  'QUANTITY_UNIT': 'Quantité',
  'WORK_DONE': 'Opérations effectuées',
  'OPERATIONS': 'Operations',
  'COMMENTS': 'Remarque',
  'MEASUREMENT_POINTS': 'Point de mesure',
  'COUNTER': 'Compteur',
  'READING_AFTER_SERVICE': 'Après réparation',
  'BEFORE_SERVICE': 'Avant réparation',
  'FROM_LAST_VISIT_ON': 'suite à la précédente intervention',
  'LMRA_ENABLED_IN_VISIT_REPORT': 'false',
  'AUTHORISATION_TO_CARRY': "Autorisation de réaliser l'intervention avec ou sans obtention d'un N° de commande client",
  'NOTES': 'Note',
  'CUSTOMER_WILL_AGREE': "Le Client s'engage à fournir à Exlair dans les deux jours ouvrés suivant le depart du technicien, un numéro de commande valide pour l'intervention effectuée",
  'CUSTOMER_CONFIRMATION': 'Confirmation client',
  'SERVICE_ENGINEER_CONFIRMATION': 'Confirmation Technicien',
  'SIGNED_BY': 'Signé par',
  'AT': 'le',
  'BEING_DULY_AUTHORISED': '(Pouvoir à été donné pour signer au nom du client)',
  'ENTER_YOUR_NAME': 'Ecrivez votre nom',

  'FAX': 'Fax',
  'TELEPHONE': 'Tél.',

  'COMPANY_GROUP_NAME': 'MultiAir France',

  'COMPANY_LEGAL_NAME': 'PA Du Vert Galant',

  'COMPANY_ADDRESS_1': '2, Avenue des Gros Chevaux',

  'COMPANY_ADDRESS_2': "95310 St Ouen L'Aumône",

  'VISITORS_ADDRESS': '',

  'VISITOR_ADDRESS_1': '',

  'VISITOR_ADDRESS_2': '',

  'FOOTER_CENTER_LINE1': 'Tel : +33 (0)1 34 32 95 00',

  'COMPANY_FAX': 'Fax : +33 (0)1 34 32 95 33',

  'COMPANY_URL': 'http://www.worthington-creyssensac.com/fr',

  'FOOTER_ADDITIONAL_INFO_1': 'Siret 388 163 099 00137 ',

  'FOOTER_ADDITIONAL_INFO_2': 'TVA FR 41 388 163 099',

  'FOOTER_ADDITIONAL_INFO_3': 'IBAN : FR 76 3000 4018 5600 0100 2341 211 ',

  //Commission report
  'COMMISSION_REPORT': 'Procédure de Mise en service',
  'COMM_INTRO': "La mise en service d'un compresseur est un événement essentiel. Son exécution est la première étape dans l'élaboration du suivi documenté de votre compresseur . Cette documentation est essentielle pour une maintenance appropriée. Lors de cette mise en service, le technicien va enregistrer les compteurs  et autres données de fonctionnement de la machine. Toutes les températures, pressions, tension, intensités, etc ... sont mesurés avec les instruments appropriés. Les données de mesure dans le rapport de mise en service seront des valeurs de référence importantes dans l'interprétation des enregistrements ultérieurs de ces mêmes données de mesure pendant les entretiens. Si ces données ne sont pas consignées lors de la mise en service, l'interprétation ultérieur de ces mêmes valeurs sera rendu plus difficile.",
'COMM_CHECK_TITLE': 'Liste de contrôle',
'COMM_CHECK': 'Contrôle',
'COMM_COMMENTS': 'Commentaires',
'COMM_Q1_Q': 'Installation réalisée par',
'COMM_Q1_A1': 'Atlas Copco',
'COMM_Q1_A2': 'Client',
'COMM_Q2_Q': 'Raccordement électrique réalisé par',
'COMM_Q2_A1': 'Atlas Copco',
'COMM_Q2_A2': 'Client',
'COMM_Q3_Q': 'Dommages constatés sur l\'équipement',
'COMM_Q3_A1': 'Oui',
'COMM_Q3_A2': 'Non',
'COMM_Q3_A3': 'Si oui, où ?',
'COMM_Q4_Q': 'De la corrosion sur l\'équipement',
'COMM_Q4_A1': 'oui',
'COMM_Q4_A2': 'Non',
'COMM_Q4_A3': 'Si oui, où ?',
'COMM_Q5_Q': 'Conditions ambiantes',
'COMM_Q5_A1': 'Propre',
'COMM_Q5_A2': 'Salle',
'COMM_Q5_A3': 'Très salle',
'COMM_Q6_Q': 'Local compresseur convenablement ventillé',
'COMM_Q6_A1': 'Oui',
'COMM_Q6_A2': 'Non',
'COMM_Q7_Q': 'Y a-t-il d\'autres compresseurs dans la même salle ',
'COMM_Q7_A1': 'Oui',
'COMM_Q7_A2': 'Non',
'COMM_Q7_A3': 'Si oui, préciser',
'COMM_Q8_Q': 'Dalle ok ?',
'COMM_Q8_A1': 'Oui',
'COMM_Q8_A2': 'Non',
'COMM_Q9_Q': 'Gainage de refoulement ou d\'aspiration utilisé ?',
'COMM_Q9_A1': 'Seulement sur l\'aspiration ?',
'COMM_Q9_A2': 'Seulement sur le refoulement ?',
'COMM_Q9_A3': 'Pour les deux ?',
'COMM_Q10_Q': 'Dimensions de l\'arrivée d\'air ok ?',
'COMM_Q10_A1': 'oui',
'COMM_Q10_A2': 'Non',
'COMM_Q11_Q': 'Collecteur de refoulement ok ?',
'COMM_Q11_A1': 'oui',
'COMM_Q11_A2': 'non',
'COMM_Q12_Q': 'Tuyauterie de refoulement ok ?',
'COMM_Q12_A1': 'Oui',
'COMM_Q12_A2': 'Non',
'COMM_Q13_Q': 'Réservoir installé',
'COMM_Q13_A1': 'oui',
'COMM_Q13_A2': 'Non',
'COMM_Q13_A3': 'Volume',
'COMM_Q13_A4': 'l',
'COMM_Q14_Q': 'Filtre installé en sortie de compresseur',
'COMM_Q14_A1': 'oui',
'COMM_Q14_A2': 'non',
'COMM_Q14_A3': 'Si oui, préciser',
'COMM_Q15_Q': 'Sécheur installé',
'COMM_Q15_A1': 'oui',
'COMM_Q15_A2': 'non',
'COMM_Q15_A3': 'Si oui, préciser',
'COMM_Q16_Q': 'Qualité de l\'eau de refroidissement ok',
'COMM_Q16_A1': 'Oui',
'COMM_Q16_A2': 'Non',
'COMM_Q17_Q': 'Débit d\'eau en l/s',
'COMM_Q17_A1': 'Oui',
'COMM_Q17_A2': 'Non',
'COMM_Q17_A3': 'l/s',
'COMM_Q18_Q': 'Evacuation des condensat dans',
'COMM_Q18_A1': 'Séparateur eau/huile',
'COMM_Q18_A2': 'Egout',
'COMM_Q19_Q': 'Tension',
'COMM_Q20_Q': 'Fréquence',
'COMM_Q21_Q': 'Réglage du relais thermique du moteur principal',
'COMM_Q22_Q': 'Réglage du relais thermique du (des) ventilateur(s)',
'COMM_Q23_Q': 'Pression de mise en charge / mise à vide',
'COMM_Q23_A1': 'bar',
'COMM_Q24_Q': 'Instruction d\'utilisation du module Elektronikon communiquée au client',
'COMM_Q24_A1': 'Oui',
'COMM_Q24_A2': 'Non',
'COMM_Q25_Q': '25.',
'COMM_Q25_A1': 'Contrôle complémentaire',
'COMM_Q26_Q': '26.',
'COMM_Q26_A1': 'Contrôle complémentaire',
'COMM_Q27_Q': '27.',
'COMM_Q27_A1': 'Contrôle complémentaire',
'COMM_Q28_Q': 'Instruments de mesure',
'COMM_Q29_Q': 'Numéro de série',
'COMM_Q30_Q': 'Numéro de certificat'
};
