export var textLiterals = {
  'VISIT_REPORT': 'Lieferschein',
  'COMMISSION_REPORT': 'Inbetriebnahmeprotokoll', //TODO: translate
  'LMRA_REPORT': 'Last Minute Risk Analysis', //TODO: translate
  'SMARTBOX_REPORT': 'Smartboxreport', //TODO: translate
  'SPM_REPORT': 'SPM Report', //TODO: translate
  'TIME_CONFIRMATION_REPORT': '',
  'CUSTOMER_DETAILS': 'Kundendaten',
  'CONTACT': 'Kontaktperson',
  'REPORT_DATE': 'Datum',
  'EQUIPMENT': 'Maschine',
  'RUNNING_HOURS': 'Betriebsstunden',
  'HOURS': 'Stunden',
  'SERIAL_NUMBER': 'Seriennummer',
  'LOAD_HOURS': 'Laststunden',
  'VISIT_DATE': 'Servicedatum',
  'ORDER_NUMBER': 'Auftragsnummer',
  'CONTRACT_NUMBER': 'Vertragsnummer',
  'PO_NUMBER': 'Kundenbestellzeichen',
  'WORK_COMMENTS': 'Arbeitsbericht',
  'NEXT_VISIT': 'Nächster Besuch',
  'NEXT_RECOMMENDED_SERVICE_1': 'Wir empfehlen das nächste Service am“',
  'NEXT_RECOMMENDED_SERVICE_2': '” durchführen zu lassen.',
  'FOLLOWING_WORK_IS': 'Wir werden Ihnen ein Angebot für diese Arbeiten zusenden..',
  'ESTIMATED_WORK_HOUR': 'Geschätze Dauer',
  'TIME_CONFIRMATION': 'Arbeitszeit',
  'DATE': 'Datum',
  'SERVICE_ENGINEER': 'Servicetechniker',
  'ACTIVITY_TYPE': 'Beschreibung',
  'HOUR_KM': 'Anzahl',
  'MATERIAL_CONFIRMATION': 'Artikelliste',
  'PART_NUMBER': 'Artikelnummer',
  'PART_DESCRIPTION': 'Bezeichnung',
  'QUANTITY_UNIT': 'Anzahl',
  'WORK_DONE': 'Durchgeführte Arbeiten',
  'OPERATIONS': 'Messwerte',
  'COMMENTS': 'Anmerkungen',
  'MEASUREMENT_POINTS': 'Messpunkte',
  'COUNTER': 'Messwert',
  'READING_AFTER_SERVICE': 'nach dem Service',
  'BEFORE_SERVICE': 'vor dem Service',
  'FROM_LAST_VISIT_ON': 'beim letzten Service',
  'AUTHORISATION_TO_CARRY': 'Auftrag zur Durchführung der Arbeiten mit/ohne Bestellnummer',
  'NOTES': 'Anmerkungen',
  'CUSTOMER_WILL_AGREE': 'Der Kunde erklärt sich einverstanden Atlas Copco am nächsten Werktag eine gültige Bestellnummer für die im Rahmen des Serviceeinsatzes erbrachten Arbeits- und Reisezeiten, sowie der verwendeten Ersatzteile zusenden.',
  'CUSTOMER_CONFIRMATION': 'Unterschrift des Kunden',
  'SERVICE_ENGINEER_CONFIRMATION': 'Unterschrift des Servicetechnikers',
  'ENTER_YOUR_NAME': 'Geben Sie Ihren Namen ein', //TODO: translate
  'PLEASE_ENTER_YOUR': 'Bitte geben Sie hier Ihren Namen ein', //TODO: translate
  'SIGNED_BY': 'Unterschrieben von',
  'AT': 'am',
  'BEING_DULY_AUTHORISED': '(rechtsverbindliche Unterschrift)',

  'SAFETY_FIRST': 'Sicherheitsfragebogen', //TODO: translate
  'QUESTION': 'Frage', //TODO: translate
  'CHECKED': 'Geprüft', //TODO: translate

  'COMPANY_GROUP_NAME': 'Atlas Copco Ges.m.b.H. Kompressoren und Drucklufttechnik',
  'COMPANY_LEGAL_NAME': 'Atlas Copco Ges.m.b.H.', //TODO: get legal name
  'VISITORS_ADDRESS': 'Office Park 1 Top B02',
  'TELEPHONE': 'Tel.',
  'COMPANY_TELEPHONE': '+43 (0)1 76012 0',
  'FOOTER_ADDITIONAL_INFO_1': 'FN 115327 z',
  'COMPANY_ADDRESS_1': 'Office Park 1 Top B02',
  'VISITOR_ADDRESS_1': 'Office Park 1 Top B02',
  'FAX': '',
  'COMPANY_FAX': '',
  'FOOTER_ADDITIONAL_INFO_2': 'UID: ATU 37209800',
  'COMPANY_ADDRESS_2': '1300 Flughafen Wien',
  'VISITOR_ADDRESS_2': '1300 Flughafen Wien',
  'COMPANY_URL': 'www.atlascopco.at',
  'FOOTER_ADDITIONAL_INFO_3': 'DVR: 040509',
  'WORKER_DETAIL': 'NL - Worker Detail',
  'WORK_CENTER': 'NL - Work Center',
  'SEARCH_OPTIONS': 'NL - Search Options',
  'DATE_FROM': 'NL -From',
  'DATE_TO': 'NL - To',
  'TOTAL': 'Total',
  'WEEK': 'Woche'
};
