export var textLiterals = {
  'VISIT_REPORT': 'Visit Report',
  'COMMISSION_REPORT': 'Commissioning Report',
  'LMRA_REPORT': 'Safety First Report',
  'LMRA_ENABLED_IN_VISIT_REPORT': 'false',
  'SMARTBOX_REPORT': 'SmartBox Installations',
  'SPM_REPORT': 'SPM Report',
  'TIME_CONFIRMATION_REPORT': 'Time Confirmation Report',
  'CUSTOMER_DETAILS': 'Customer Details',
  'CONTACT': 'Contact',
  'REPORT_DATE': 'Report date',
  'EQUIPMENT': 'Equipment',
  'RUNNING_HOURS': 'Running Hours',
  'HOURS': 'hours',
  'SERIAL_NUMBER': 'Serial Number',
  'LOAD_HOURS': 'Load Hours',
  'VISIT_DATE': 'Visit date',
  'ORDER_NUMBER': 'Order Number',
  'CONTRACT_NUMBER': 'Contract Number',
  'PO_NUMBER': 'PO number',
  'WORK_COMMENTS': 'Work Comments',
  'NEXT_VISIT': 'Next Visit',
  'NEXT_RECOMMENDED_SERVICE_1': 'Next recommended service is a “',
  'NEXT_RECOMMENDED_SERVICE_2': '” estimated due date',
  'FOLLOWING_WORK_IS': 'Following work is recommended, our service sales will contact you',
  'ESTIMATED_WORK_HOUR': 'Estimated work hour',
  'TIME_CONFIRMATION': 'Time Confirmation',
  'DATE': 'Date',
  'SERVICE_ENGINEER': 'Service Engineer',
  'ACTIVITY_TYPE': 'Activity Type',
  'HOUR_KM': 'Hour/km',
  'MATERIAL_CONFIRMATION': 'Material Confirmation',
  'PART_NUMBER': 'Part Number',
  'PART_DESCRIPTION': 'Part Description',
  'QUANTITY_UNIT': 'Quantity unit',
  'WORK_DONE': 'Work Done',
  'OPERATIONS': 'Operations',
  'COMMENTS': 'Comments',
  'MEASUREMENT_POINTS': 'Measurement Points',
  'COUNTER': 'Counter',
  'READING_AFTER_SERVICE': 'Reading after service',
  'BEFORE_SERVICE': 'Before service',
  'FROM_LAST_VISIT_ON': 'From last visit on',
  'AUTHORISATION_TO_CARRY': 'AUTHORIZATION TO CARRY OUT WORK WITH/WITHOUT AN ORDER NO.',
  'NOTES': 'Notes',
  'CUSTOMER_WILL_AGREE': 'Customer will agree to supply Atlas Copco with a valid order number or payment for non-account holders for actual time spend, travelling and parts used during the breakdown intervention by next working day.',
  'CUSTOMER_CONFIRMATION': 'Customer Confirmation',
  'SERVICE_ENGINEER_CONFIRMATION': 'Service Engineer Confirmation',
  'ENTER_YOUR_NAME': 'Enter your name',
  'PLEASE_ENTER_YOUR': 'Please enter your name here',
  'SIGNED_BY': 'Signed by',
  'AT': 'at',
  'BEING_DULY_AUTHORISED': '(Being duly authorised to sign on behalf of the customer)',

  'SAFETY_FIRST': 'Safety First',
  'QUESTION': 'Question',
  'CHECKED': 'Checked',
  'COMPANY_GROUP_NAME': 'Atlas Copco Compressors Nederland',
  'COMPANY_LEGAL_NAME': '',
  'VISITORS_ADDRESS': 'Visitors\' address',
  'TELEPHONE': 'Tel',
  'COMPANY_TELEPHONE': '+31 (0)78 6230 230',
  'FOOTER_ADDITIONAL_INFO_1': 'Deutsche Bank 26.51.37.527',
  'COMPANY_ADDRESS_1': 'Merwedeweg 7',
  'VISITOR_ADDRESS_1': 'Postbus 200',
  'FAX': 'Fax',
  'COMPANY_FAX': '+31 (0)78 6230 242',
  'FOOTER_ADDITIONAL_INFO_2': 'BTW nr.\tNL.00.6958.369.B01',
  'COMPANY_ADDRESS_2': '3336 LG Zwijndrecht',
  'VISITOR_ADDRESS_2': '3330 AE Zwijndrecht',
  'COMPANY_URL': 'www.atlascopco.nl',
  'FOOTER_ADDITIONAL_INFO_3': 'Handelsreg.\t23051060 Dordrecht',
  'WORKER_DETAIL': 'Worker Detail',
  'WORK_CENTER': 'Work Center',
  'SEARCH_OPTIONS': 'Search Options',
  'DATE_FROM': 'From',
  'DATE_TO': 'To',
  'TOTAL': 'Total',
  'WEEK': 'Week'
};
